### ISSUE TITLE
[Close chat confusion] Remove the composer after df_close_chat payload

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1019]
Currently we will be showing the "Close chat" button, which will close the chat. 

It might be the case that we want to consolidate on a single way to close the widget by clicking the "x".

To do this we would want to remove the composer entirely upon receiving the df_close_chat payload.

**Comment by ear-dev** [comment]
NOTE: we do not want to do this in mobile.  We need to maintain the current mobile behavior.

**Comment by ear-dev** [comment]
@bhardwajaditya is this possible?  Would it cause any issues?

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 Can you comment please on the feasibility of this design? What do you think?

**Comment by bhardwajaditya** [comment]
@ear-dev Sorry missed this earlier, I think we can stop rendering that when room is closed

**Comment by ear-dev** [comment]
Solution:  In all cases when we receive the df_close_chat payload we will remove the composer entirely, instead of using the "Close Chat" or "Please close this chat to end your session" buttons.

**Comment by ear-dev** [comment]
@AlexanderKanakis any progress on this?  Maybe if you are busy with other stuff @bhardwajaditya or @Shailesh351 can take this one?  This is blocking a DF.agent promotion and the team would like to resolve.  Thanks.

**Comment by AlexanderKanakis** [comment]
PR:
Rocket.Chat.Livechat: https://github.com/WideChat/Rocket.Chat.Livechat/pull/119
