### ISSUE TITLE
in escalation failure: check to see if room is closed before trying to close it

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#1025]
DF App - Handover to SF App - SF tries to find live agent - SF App Fails to find live agent - SF closes room - SF than sends event to DF Agent which is configured in SF App Settings - In the response we got df_close_chat which shows above error

one solution is to check to see if the room is closed before closing it.

**Comment by AlexanderKanakis** [comment]
@chadgoss are you refering to the event set in the `Dialogflow Agent Unavailable Event Name` setting?

**Comment by chadgoss** [comment]
@AlexanderKanakis yep

**Comment by AlexanderKanakis** [comment]
PR:

Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/126
