### ISSUE TITLE
[DF.app] Add a UI config item that we can set to disable the wait for welcome intent, so that the composer is available immediately

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1030]
We would like to use the widget for some of the automated testing against Brazil CX agents which were designed for whatsApp.  So in this use-case, we do not want to wait for a welcome intent before making the composer available for typing.

**Comment by ear-dev** [comment]
Need this for brazil bot

"disable_composer_on_trigger_event" - true (UsRes), false (Brazil)

**Comment by ear-dev** [comment]
@bhardwajaditya I moved this back into in progress.  When you have adjusted the PR please move back into Under Review, so I will know it is ready.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev it's ready and moved it back to under review
