### ISSUE TITLE
[RC API] Add user_status to user creation endpoint.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1034]
We want the ability to create new users that are online immediately.

**Comment by AlexanderKanakis** [comment]
PR:

Rocket.Chat: https://github.com/WideChat/Rocket.Chat/pull/1035

## Note:
Please merge asap to avoid merging issues with the new REST API required in https://github.com/WideChat/Rocket.Chat/issues/1031
