### ISSUE TITLE
[Test Integration Widget] Add a test whatsApp number to the testWidget.html for our integration test bed.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1038]
In our CI/CD pipeline, we will be using test widgets modeled after Shailesh's html file. Ask shailesh for a copy if needed.  
We will be using livechat widgets to test CX agents in our pipeline, but we want to simulate WhatsApp as best possible.......  i.e. we will need to include a fake whatsApp number as the username, so that it gets passed to CX.agent as if this were a whatsApp session.

**Comment by AlexanderKanakis** [comment]
PRs:

Rocket.Chat: https://github.com/WideChat/Rocket.Chat/pull/1084
Rocket.Chat.Livechat: https://github.com/WideChat/Rocket.Chat.Livechat/pull/127
Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/134

Test Widget: https://github.com/WideChat/Rocket.Chat.IntegrationTests/tree/master/test_widgets/whatsapp_phone_number_test

### Note:
Please run `meteor npm install @rocket.chat/livechat` on your RC repo.

**Comment by ear-dev** [comment]
@bhardwajaditya can you please review these three PRs.  Thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis please decouple the token widget functionality from the whatsApp  number stuff.  "going back to the original"

**Comment by ear-dev** [comment]
@AlexanderKanakis I've tested the phone number as username PRs and it looks good.  I just want to be sure that we have not broken the original use case with a real whatsApp conversation through twilio.  Did you test for that?  Thanks.
