### ISSUE TITLE
[BUG] Fix print option in the widget.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1043]
We may have inadvertently removed it in this PR:  https://github.com/WideChat/Rocket.Chat.Livechat/pull/119

**Comment by AlexanderKanakis** [comment]
@ear-dev  on it.

**Comment by AlexanderKanakis** [comment]
PR:

Rocket.Chat.Livechat: https://github.com/WideChat/Rocket.Chat.Livechat/pull/121
