### ISSUE TITLE
[Test Integration Widget] Enhance our html to include the passing of real tokens.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1067]
We are using an html with an embedded livechat widget for our test bed bundles.  We need to have the option to pass a real user token upon session registration, just like the my.viasat app does.

One suggestion was to add an drop down in the html that we could use to manually set the token.

**Comment by ear-dev** [comment]
@AlexanderKanakis please host your widget work in this repo under a new "test_widget" directory:  https://github.com/WideChat/Rocket.Chat.IntegrationTests

This issue is linked to issue number 1038

**Comment by ear-dev** [comment]
UsRes use-case:

- simulator: we can use hard coded tokens that will be recognized by our backend
- real test users: these are real accounts from SSO and for these will need an api to the real SSO server to get a fresh token from one of the test users.

**Comment by AlexanderKanakis** [comment]
Test Widget with hard-coded tokens: https://github.com/WideChat/Rocket.Chat.IntegrationTests/tree/master/test_widgets/token_test

**Comment by ear-dev** [comment]
@AlexanderKanakis please add the functionality to make a real api call to SSO to obtain a real token that you can push to the function in the html  custom_field.
example:
https://github.com/WideChat/Rocket.Chat.IntegrationTests/blob/master/cypress/support/commands.js#L34

**Comment by AlexanderKanakis** [comment]
PR: 

Rocket.Chat.IntegrationTests: https://github.com/WideChat/Rocket.Chat.IntegrationTests/pull/3

**Comment by ear-dev** [comment]
@AlexanderKanakis please document your CORS issue here.

**Comment by AlexanderKanakis** [comment]
### REQUEST
```
const response = await fetch('https://mysso.my.test.viasat.com:443/federation/json/realms/root/realms/myviasat/authenticate', {
			method: 'post',
			headers: {
				"Content-Type": "application/json",
				"X-OpenAM-Username": u,
				"X-OpenAM-Password": p,
				"Accept-API-Version": "resource=2.0, protocol=1.0",
			},
		})
		.then(res => {
			return res.json();
		}).then(res => {
			alert('Login Successful')
			document.getElementById('number-input').value = '';
			document.getElementById('token-gen').value = res.tokenId;
});
```
<hr>

### CORS ISSUES

1. **When test is run locally**: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mysso.my.test.viasat.com/federation/json/realms/root/realms/myviasat/authenticate. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 405.`
2. **When test is run online** (ngrok): `Access to fetch at 'https://mysso.my.test.viasat.com/federation/json/realms/root/realms/myviasat/authenticate' from origin 'https://04b8-2a02-85f-f0d9-b000-1407-b770-c5be-724f.ngrok.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

**Comment by ear-dev** [comment]
@bhardwajaditya can you test this widget please and see if anything stands out to you as a fix?

**Comment by ear-dev** [comment]
@AlexanderKanakis testing this, I see that I can generate a token, but the goal here is to pass the token into the custom field upon starting a chat. We basically want to emulate what happens in the real widget when it is embedded into the myViasat app.  In production we pass two custom fields (below) and those fields are required by our backend to authenticate viasat users.  

Can you add this functionality?  Thanks. 

```
RocketChat(function () {
		// const appName = "WidgetItbTest";
		// const token = "something-anything";

		this.setDepartment('Viasat Virtual Assistant');
		this.minimizeWidget();
      	// this.maximizeWidget();

		
		// this.setCustomField('appName', appName);
		// this.setCustomField('token', token);

		this.onChatStarted(() => {
			console.log("onChatStarted fn")
		});
```

**Comment by AlexanderKanakis** [comment]
@ear-dev It should be covered with 
```
  const phone = document.getElementById('number-input').value;
  const token = document.getElementById('token-gen').value;
  if (phone !== '') {
	  this.setGuestPhone(phone);
  }
  if (token !== '') {
	  this.setGuestToken(token.value);
  }
```

Are you not able to see the token?

Reminder: we also need to merge this: https://github.com/WideChat/Rocket.Chat.Livechat/pull/127

**Comment by ear-dev** [comment]
oh interesting....  somehow it completely escaped me that there was a livechat portion of the fix.  I'll test with that.  Thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis where would I find that code block you mentioned above?  is it in one of the PRs, or is it supposed to be in the widget?

```
const phone = document.getElementById('number-input').value;
  const token = document.getElementById('token-gen').value;
  if (phone !== '') {
	  this.setGuestPhone(phone);
  }
  if (token !== '') {
	  this.setGuestToken(token.value);
  }
```

**Comment by AlexanderKanakis** [comment]
In the widget

**Comment by ear-dev** [comment]
oh man.......  I'm not even working off of your PR, but was looking at the master branch......  sorry.....  testing again.

**Comment by ear-dev** [comment]
@AlexanderKanakis are you sure that the Livechat PR is up to date?  I think I only see the setGuestPhone function and not setGuestToken.

**Comment by AlexanderKanakis** [comment]
@ear-dev The setGuestToken function already existed.

**Comment by ear-dev** [comment]
@Shailesh351 can you verify please what are exactly the contents of the 'token' that we pass in customFields from the myViasat widget?  Is that the authentication token from the original mySSO login?  

I'm testing this new widget, and I'm able to get an authentication token into our test widget and passed into customFields, and initially it seems like the CX.agent is happy with it because it does not show me that "Demo User" message.  But subsequent calls to something like 'data usage' is returning that "unable to locate my account information" message....  making me think that there is some other step required for passing in user identity.  Thanks.

**Comment by ear-dev** [comment]
It looks like the myViasat integration script does this:
```
useEffect(() => {
    if (isScriptLoaded && token?.accessToken) {
      setCustomFields([
        { name: 'appName', value: APP_NAME },
        { name: 'token', value: token?.accessToken ?? '' },
      ]);
```
I suspect maybe that the actual 'token' we are looking for is some property of the original tokenId which is returned from our POST to mysso.my.test.viasat.com. "token?.accessToken".  In the myViasat case, I can see a bunch of subsequent graphql calls, and maybe that's where our token comes from.  We'll need to investigate. 

Confirmed:  The tokenId needs to be used on subsequent calls to SSO to get an accessToken, and that is what we need to put into the customField to make this work.  I'll continue to investigate.

**Comment by ear-dev** [comment]
UPDATE:  Since Viasat is in the process of moving away from mysso and to a new system 'okta', we're going to put this task aside for now and deal with it after the Okta transition.  Sorry for the confusion.  In the meantime, I will start looking at the whatsApp number implementation and see how that works.  Thanks!
