### ISSUE TITLE
[Cypress tests] Create a github actions workflow that will run a suite of tests against a given url/widget

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1069]

**Comment by bhardwajaditya** [comment]
Cypress provides a well documented and managed library to run automatic test suits via GitHub Actions.
https://docs.cypress.io/guides/continuous-integration/github-actions#Cypress-GitHub-Action

The key points to discuss is:
- When to trigger these tests
- Currently cypress supports Chrome, Firefox, edge and other chromium based browsers. Which all to be considered for the tests.

**Comment by ear-dev** [comment]
@bhardwajaditya please start by creating a manual trigger `workflow_dispatch` later on we will automate the trigger once we have gone further with our automation design.   Chrome only is fine.
