### ISSUE TITLE
[BUG][DF.app] Changing values in the config requires a server restart for the changes to take effect.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1074]
If I make a change in the config.json in the Admin UI, and hit the save button, the changes do not take effect until a server restart.  I have not tested this with the API, but it should not require a server restart in either case. 

@AlexanderKanakis  can you verify that you are seeing the same behavior and fix if needed?  Also can you verify if this is also an issue when using the API please.  Thanks.

**Comment by AlexanderKanakis** [comment]
@ear-dev  I can confirm without testing that updating settings in the UI is inconsistent at times. I can also confirm that this is not an issue with the API. Will look further into it.

**Comment by ear-dev** [comment]
Awesome!  thanks....

**Comment by ear-dev** [comment]
Alexander will adjust the logic to replace the settings instead of update in the case we make changes in the admin UI.

**ISSUE**: sometimes we can see that the mongodb has been updated correctly, but the app itself is not using the new config, and it requires a server restart to pick it up.

**Comment by ear-dev** [comment]
NOTE:  Alexander not able to reproduce yet locally. 

@Shailesh351 in brazil prod we also saw a situation recently where we seem to have lost our enterprise credentials and the cloud workspace noticed and unregistered us.  Those values in the db are here: 

https://github.com/RocketChat/Rocket.Chat/blob/6fbd7f1614da4eb109252a3c01028e2b04c7ce6a/app/cloud/server/functions/unregisterWorkspace.js#L10-L16

Is it possible that we are seeing another flavor of the issue you mentioned above: 
"ISSUE: sometimes we can see that the mongodb has been updated correctly, but the app itself is not using the new config, and it requires a server restart to pick it up."

**Comment by ear-dev** [comment]
@AlexanderKanakis I am now seeing an issue fairly consistently where after configuring a new CX agent endpoint it seems to be failing to recognize it, even when I use the api to do it.  Even after restarting the RC server, I see this error in the DF logs...
```
[
  "{\"stack\":\"Error: Error: Agent cx-test-agent not found in Dialogflow Agent Endpoints\\n    at Cs (evalmachine.<anonymous>:1:13888)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at so.run (evalmachine.<anonymous>:8:11922)\\n    at Vo.executePostLivechatAgentAssigned (evalmachine.<anonymous>:8:27339)\",\"message\":\"Error: Agent cx-test-agent not found in Dialogflow Agent Endpoints\"}"
]
```

Any idea what might be going on?
