### ISSUE TITLE
[Bug] Empty rid and token in getTranscript

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1076]
```
Jan 31, 2022 @ 19:51:42.195	Invalid room [error-invalid-room]
Jan 31, 2022 @ 19:51:42.194	getTranscript: Room/Token not valid or Visitor token not allowed to access the room. {"rid":"","token":""}
```

this is probably a bug on the fullfillment side, where if we have a missing appName/token, we don't collect roomId and visitorToken

but very suspicious that we did an RC update on the 13th so RC Issue?

**Comment by chadgoss** [comment]
sessions in the last 24 hours where we've seen this:

Gucyzsg7oML5nwiyB
A9ToJziXTJWmA5QCv
RP3YkfTgQuECLjcjT
7oGrPPY2Ny6NWaoeZ
taXWKyk4Xxda9MM5Z
s5WHMLjxHanKHPxet
YuuEyqGMm9CJZ8ASP
hrcwcYGcC2r7q7jmc
9fxdcaizyw2QLEMrT
7DupC8qhy9gGJ4fSb
bD8q2oFnytm2aMcu8
wcjJLWRNNSZA44FNB
ePzE9GhQ8ungspTEr
R8Ej39gXPWgDpH6Mk

**Comment by chadgoss** [comment]
in every single case, here's the request/response:

webhook request Welcome event with empty appName/token
`Webhook Request: {'responseId': '07f0fbec-73a3-4874-a167-e6be93484453-c8e3f272', 'queryResult': {'queryText': 'Welcome', 'action': 'load_subscriber_info', 'parameters': {'roomId': 'RP3YkfTgQuECLjcjT', 'visitorToken': 'c29r8ym37lhqguu7dlwdqh', 'appName': '', 'token': ''}`

Webhook response with text and df_close_chat payload
`Webhook Response: ({'outputContexts': [{'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/chat_source_MyViasatWebAmer', 'lifespanCount': 999, 'parameters': {'app': 'MyViasatWebAmer', 'device_type': '', 'page_url': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/previous_intent_info', 'lifespanCount': 999, 'parameters': {'roomId': 'RP3YkfTgQuECLjcjT', 'visitorToken': 'c29r8ym37lhqguu7dlwdqh', 'appName': '', 'token': ''}}], 'fulfillment_messages': [{'text': {'text': ['I am unable to locate your account information.']}}, {'text': {'text': ['Please contact our Customer Care team by phone 24/7 at 1-855-463-9333.']}}, {'text': {'text': ['Please close this window to end your chat session.']}}, {'type': 4, 'condition': '', 'payload': {'action': {'name': 'df_close_chat'}}, 'lang': 'en'}],`


Webhook request with text from user?
`views.webhook: [Session_ID: RP3YkfTgQuECLjcjT] Webhook Request: {'responseId': '82165338-2411-4659-952c-4d33840bdd19-c8e3f272', 'queryResult': {'queryText': 'Cancel services', 'parameters': {'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request'}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'payload': {'invokeClass': 'NF_GenerateViasatCase'}}, {'payload': {'followup': {'delay': 2000.0, 'event': 'go_to_a_cancel_service'}}}, {'payload': {'disableInput': True, 'disableInputMessage': 'Please wait'}}, {'payload': {'customFields': {'disableInput': True, 'disableInputMessage': 'Please wait', 'displayTyping': True}}}], 'outputContexts': [{'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/to_a_cancel_service', 'lifespanCount': 1, 'parameters': {'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/chat_source_myviasatwebamer', 'lifespanCount': 998, 'parameters': {'app': 'MyViasatWebAmer', 'device_type': '', 'page_url': '', 'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/previous_intent_info', 'lifespanCount': 998, 'parameters': {'appName': '', 'roomId': 'RP3YkfTgQuECLjcjT', 'visitorToken': 'c29r8ym37lhqguu7dlwdqh', 'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}], 'intent': {'name': 'projects/chatbot-prod-228818/agent/intents/732f6846-46f7-11ec-9f5a-0242ac110003', 'displayName': 'g_account_cancel_service_deflection'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'payload': {}}, 'session': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT'}`

**Comment by ear-dev** [comment]
Two issues:

- Fulfillment bug: @chadgoss will make JIRA and fix - if appName and Token are missing, fulfillment not storing the roomId and visitorToken which is needed for getTranscript.
- Suddenly on jan13 we started to see logging for this issue from RC.  Is there a bug, or are we just now catching it properly.......  TODO: review the new RC server version for changes that might account for this, or caused an actual issue?
