### ISSUE TITLE
[Blocked on Chad fix in fulfillment] df_close_chat payload not closing room

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#1077]
This seems to be a new flavor of the issue Aditya fixed that prevents the user from triggering a new room when the composer does not disappear properly.  In this case the RC server seemed to not close the room after it received the df_close_chat payload.  So the user typed into the open composer and the chat just continued by trying to escalate, even though fulfillment think we are starting a new session......  and this new session has no appname/token.

**Comment by chadgoss** [comment]
in every single case, here's the request/response:

webhook request Welcome event with empty appName/token
`Webhook Request: {'responseId': '07f0fbec-73a3-4874-a167-e6be93484453-c8e3f272', 'queryResult': {'queryText': 'Welcome', 'action': 'load_subscriber_info', 'parameters': {'roomId': 'RP3YkfTgQuECLjcjT', 'visitorToken': 'c29r8ym37lhqguu7dlwdqh', 'appName': '', 'token': ''}`

Webhook response with text and df_close_chat payload
`Webhook Response: ({'outputContexts': [{'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/chat_source_MyViasatWebAmer', 'lifespanCount': 999, 'parameters': {'app': 'MyViasatWebAmer', 'device_type': '', 'page_url': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/previous_intent_info', 'lifespanCount': 999, 'parameters': {'roomId': 'RP3YkfTgQuECLjcjT', 'visitorToken': 'c29r8ym37lhqguu7dlwdqh', 'appName': '', 'token': ''}}], 'fulfillment_messages': [{'text': {'text': ['I am unable to locate your account information.']}}, {'text': {'text': ['Please contact our Customer Care team by phone 24/7 at 1-855-463-9333.']}}, {'text': {'text': ['Please close this window to end your chat session.']}}, {'type': 4, 'condition': '', 'payload': {'action': {'name': 'df_close_chat'}}, 'lang': 'en'}],`


Webhook request with text from user?
`views.webhook: [Session_ID: RP3YkfTgQuECLjcjT] Webhook Request: {'responseId': '82165338-2411-4659-952c-4d33840bdd19-c8e3f272', 'queryResult': {'queryText': 'Cancel services', 'parameters': {'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request'}, 'allRequiredParamsPresent': True, 'fulfillmentMessages': [{'payload': {'invokeClass': 'NF_GenerateViasatCase'}}, {'payload': {'followup': {'delay': 2000.0, 'event': 'go_to_a_cancel_service'}}}, {'payload': {'disableInput': True, 'disableInputMessage': 'Please wait'}}, {'payload': {'customFields': {'disableInput': True, 'disableInputMessage': 'Please wait', 'displayTyping': True}}}], 'outputContexts': [{'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/to_a_cancel_service', 'lifespanCount': 1, 'parameters': {'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/chat_source_myviasatwebamer', 'lifespanCount': 998, 'parameters': {'app': 'MyViasatWebAmer', 'device_type': '', 'page_url': '', 'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/previous_intent_info', 'lifespanCount': 998, 'parameters': {'appName': '', 'roomId': 'RP3YkfTgQuECLjcjT', 'visitorToken': 'c29r8ym37lhqguu7dlwdqh', 'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}, {'name': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT/contexts/__system_counters__', 'parameters': {'no-input': 0.0, 'no-match': 0.0, 'intent_name': 'g_account_cancel_service_deflection', 'input_context_names': 'to_g_account_cancel_service_deflection', 'output_context_names': 'to_a_cancel_service', 'topic': 'Account', 'deflect_to_call_in': 'true', 'intent_classification': 'account__cancellation_request__cancellation_request', 'intent_name.original': '', 'input_context_names.original': '', 'output_context_names.original': '', 'topic.original': '', 'deflect_to_call_in.original': '', 'intent_classification.original': ''}}], 'intent': {'name': 'projects/chatbot-prod-228818/agent/intents/732f6846-46f7-11ec-9f5a-0242ac110003', 'displayName': 'g_account_cancel_service_deflection'}, 'intentDetectionConfidence': 1.0, 'languageCode': 'en'}, 'originalDetectIntentRequest': {'payload': {}}, 'session': 'projects/chatbot-prod-228818/agent/environments/PRODAmerRC/users/-/sessions/RP3YkfTgQuECLjcjT'}`

**Comment by ear-dev** [comment]
Debug ideas:

Is there an issue between fulfillment and ES which might account for missing webhooks getting to RC?

Look for status of fulfillment request inside the response from ES.  And if it was a bad response log as an error. 
https://cloud.google.com/dialogflow/es/docs/reference/rest/v2/DetectIntentResponse

@ear-dev Debug on client side?  - use client side logging and try to catch one of these events and confirm if in fact the df_close_chat event showed up.

**Comment by ear-dev** [comment]
We verified that we did not see the livechatRoomCloseHandler log point for an instance of this problem.  Chad verified that fulfillment sent it to ES, and since RC got the room close text message, we assume that RC got the close room payload, but did not process it. 

Payload from fulfillment to ES:

```
'fulfillment_messages': [{'text': {'text': ['I am unable to locate your account information.']}}, {'text': {'text': ['Please contact our Customer Care team by phone 24/7 at 1-855-463-9333.']}}, {'text': {'text': ['Please close this window to end your chat session.']}}, {'type': 4, 'condition': '', 'payload': {'action': {'name': 'df_close_chat'}}, 'lang': 'en'}], 'followupEventInput': {}}, 200)
```

This is a successful df_close_chat payload from fulfillment: Notice: the good one does not include 'type' or 'condition'

```
[03/10/2022 04:21:16 PM] [PAYLOAD] in views.webhook: [Session_ID: JZGQ6G4LAYdcrNA3m] Webhook Response: ({'outputContexts': [], 'fulfillment_messages': [{'text': {'text': ['Thanks for contacting Viasat Customer Care. We appreciate your business.']}}, {'text': {'text': ['Please close this window to end your chat session.']}}, {'payload': {'action': {'name': 'df_close_chat'}}}], 'followupEventInput': {}}, 200)
```

**Comment by ear-dev** [comment]
@chadgoss will remove type and condition from the problematic df_close_chat use case.  We will verify after that.
