### ISSUE TITLE
[Livechat][New Custom Field] Pass the new field to the SF.app to include when it starts a new escalated chat.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1078]
Steve Stetak  3:29 PM
@Eric Rosenthal We had a discussion with Mark and Rahul about including the app version in the chatbot transcripts. To do this:
1) Mark will set a new custom field when starting rocket.chat that has the version
2) Rahul is going to add a field to the Salesforce transcript record
3) Rocketchat will need to pass along the custom field to the Salesforce RC app to include when it starts the chat - we may want to do this in a generic way as well

**Comment by ear-dev** [comment]
NOTE: I think that we just need to handle the new custom field in the same way we do now with 'appName' and 'token', then let CX handle it.

**Comment by ear-dev** [comment]
name of field......  'appVersion'

**Comment by AlexanderKanakis** [comment]
PRs:
Apps.Salesforce.LiveAgent: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/54

Added new custom field sent to the salesforce agent through prechatDetails.

The app version is picked from the `ILivechatRoom.customDetails.appVersion` upon handover request.

**Comment by ear-dev** [comment]
@AlexanderKanakis please verify that we can actually do this by just adding a new customField in the RC UI. 
No need to involve SF.app at all, we just want to pass the new customField as a parameter to DF.

**Comment by AlexanderKanakis** [comment]
PR: 

https://github.com/WideChat/Apps.Dialogflow/pull/147
