### ISSUE TITLE
[Bug] On App Deployment the App can randomly disable itself.

### ISSUE THREAD

**Issue by AlexanderKanakis** [WideChat/Rocket.Chat#1079]

**Comment by ear-dev** [comment]
NOTE: This will be fixed with the next apps-engine catchup PR.

https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/48

https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/473

**Comment by ear-dev** [comment]
@Shailesh351 can you add this dependency hash to our current develop_pwa branch please.
