### ISSUE TITLE
[BUG] Visitor Abandonment not working on the Brazil instance in prod.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1082]
Visitor abandonment is working on the UsRes instance, but since the upgrade on 1/31 it is not working on the Brazil instance. Both servers running the same versions. 

I will try restarting the Brazil instance to see if that fixes.

**Comment by ear-dev** [comment]
@Shailesh351 can you take a look at the logs in the prod kibana to see if there is any indication of an issue please?  I suppose this could be one of those situations where something is not being applied properly without a restart?  If so we should try to isolate and fix.  thanks.

**Comment by ear-dev** [comment]
@Shailesh351 also, can you recommend the best method for closing all the currently open omnichannel rooms?  we've accumulated about 5k of them and we need to get them closed once we get Visitor Abandonment working again. I wonder if this might be a good feature candidate we should put on our board..  "ability to close all open rooms"

UPDATE:  using this feature actually worked well to clear all the open rooms, so that is taken care of.

![image](https://user-images.githubusercontent.com/28864717/152885141-d278a71a-a05d-4095-9b40-829e24daef86.png)

**Comment by ear-dev** [comment]
UPDATE:  It appears that VA is not working because our connectivity services got into a bad state.  Even though it appears like our enterprise license has been applied, connectivity will not let me sync with the cloud console.  I think I've seen this before.....  wonder if it's a known issue upstream. 

This is how it looks on the brazil instance, vs. the UsRes instance:

![image](https://user-images.githubusercontent.com/28864717/152893329-49e672f4-db73-4a18-9882-3f74eb60c22b.png)


![image](https://user-images.githubusercontent.com/28864717/152893373-55f04175-776b-4302-8828-188053b4c6dc.png)

**Comment by Shailesh351** [comment]
@ear-dev The issue of Setting not being applied without restart mostly happens on App settings. I haven't seen it on server settings. So this issue is mostly not because of it.

I didn't see any logs regarding this issue in Kibana.

Looks like this Connectivity Service is the issue

**Comment by ear-dev** [comment]
Note: this has been fixed with help from the RC team.  They had to send me a new token and regenerate our license.  The new token allowed us to connect to our workspace and the new license got us working again after sync.  
In the case that this happens again I am going to save off all the db settings related to connectivity to cloud workspace and if we have to we will manually populate the db if this happens again.
