### ISSUE TITLE
[regression CX] did we lose the fix for back to back timer payloads?

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1091]
Currently we are failing the timer payload test.

```
{
  "action": {
    "name": "df_set_timeout",
    "params": {
      "time": "0",
      "eventName": "payload1"
    }
  }
}
```
that same page has an event handler that recieves payload1 back from RC and transitions to a new page, which triggers payload 2
```
{
  "action": {
    "params": {
      "eventName": "payload2",
      "time": "0"
    },
    "name": "df_set_timeout"
  }
}
```

**Comment by Shailesh351** [comment]
@ear-dev We have not handled this case for timer payloads, We did it for the incoming endpoint. I'm looking into it 👍

**Comment by ear-dev** [comment]
@Shailesh351 can you also prioritize this one please?  :-)

**Comment by Shailesh351** [comment]
@ear-dev Currently working on this one only🙂

**Comment by ear-dev** [comment]
Thanks.....  turns out this one is messing up one of the flows in prod

**Comment by ear-dev** [comment]
@Shailesh351 can you describe the bug that is fixed here?  i.e. why weren't we handling the back to back timer payloads correctly and what we needed to fix?

**Comment by Shailesh351** [comment]
@ear-dev We were not processing actions we receive as a response, we were just sending msgs. Earlier this was the case with the incoming endpoint and we fixed that. 

Now we are using https://github.com/Shailesh351/Apps.Dialogflow/blob/17b7c282a3505a8bd27e3661dda124b1d288033c/lib/payloadAction.ts#L117 which handles both actions and msgs
