### ISSUE TITLE
[ES to CX Migration] Verify if our DF.app in CX mode handles escalations

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1107]
We have a test on the testbot to test escalations with the  "df_perform_handover" payload. 
- Verify that the testbot escalation test is valid.
- Configure the CX bot with a "salesforce department" for handover.
- Verify if handover works.

**Comment by ear-dev** [comment]
NOTE: Shailesh verified that the testbot test case is not valid yet.  Talk to molly.  missing the custom payload, only receiving the text

**Comment by ear-dev** [comment]
@Shailesh351 can you take another look at this please?  We now think that the testbot should be sending the same payload we are getting in the ES case to trigger escalations.  Unless there is something about the escalation workflow we are missing, it seems like escalation does not work in our current CX app?  Thanks.

**Comment by Shailesh351** [comment]
@ear-dev I added logs to check what we are getting from DF. And it shows we are only receiving text.

<img width="394" alt="Screenshot 2022-02-28 at 5 07 36 PM" src="https://user-images.githubusercontent.com/18264684/155977174-405899e3-6625-412c-acaa-006fdd403d94.png">


```
W20220228-17:06:34.887(5.5)? (STDERR) PostMessageSentHandler
W20220228-17:06:34.888(5.5)? (STDERR) hello
W20220228-17:06:34.888(5.5)? (STDERR) {"isFallback":false,"messages":[{"text":"Hello, this is the RocketChat Test Bot (not the real BrazilBot or any clone)"}],"parameters":{"visitorToken":"d92558bea3d394eeda16ea2fed2c86ae2517bab1024edbb1ef9d631025b62753","roomId":"AsasHpWxBDLPK5LnZ","username":"guest-890"}}
W20220228-17:07:01.578(5.5)? (STDERR) PostMessageSentHandler
W20220228-17:07:01.578(5.5)? (STDERR) handover
W20220228-17:07:01.580(5.5)? (STDERR) {"isFallback":false,"messages":[{"text":"firing handoff payload"}],"parameters":{"visitorToken":"d92558bea3d394eeda16ea2fed2c86ae2517bab1024edbb1ef9d631025b62753","username":"guest-890","roomId":"AsasHpWxBDLPK5LnZ"}}
```

In other tests we are receiving action payload properly. i.e. `Close chat`

```
W20220228-17:25:27.692(5.5)? (STDERR) PostMessageSentHandler
W20220228-17:25:27.693(5.5)? (STDERR) close chat
W20220228-17:25:27.693(5.5)? (STDERR) {"isFallback":false,"messages":[{"text":"Closing the chat/RC room"},{"action":{"name":"df_close_chat"}}],"parameters":{"visitorToken":"e3500df631696b49c8079357c5d58eadd77cab8239161418a07795048d0de0ab","username":"guest-893","roomId":"WjtPnnqkgC3hnjRPA"}}
```

**Comment by ear-dev** [comment]
Ok cool, thanks for checking..... for some reason Molly is convinced we're sending the payload, but I'll check back with her and show the logs.

**Comment by Shailesh351** [comment]
@ear-dev I have checked the payload we are receiving and it was invalid.

Instead of 
```
{ action:{...}}
```
we are receiving 
```
{payload: { action:{...}}}
```

I have updated it in the draft but I'm not seeing any effect(still receiving with {payload:{...}}). Maybe Molly can deploy changes?

**Comment by ear-dev** [comment]
@Shailesh351 after fixing the payload it does appear that our CX app is escalating and doing the handover to the SF app.  That is good.  But we are failing to escalate to Salesforce itself, which I think should work right now against the dev server.  i.e. The SF.app is configured just like the SF.app in our preprod server where escalations are working.  We must be either missing something in the payload, or we're not quite configured properly?  

What I am seeing is the "Sorry we are unable to complete your request right now." message, which is configured in the SF.app itself.  Can you take a look when you have a minute please?  I'd like to figure out why we can't successfully escalate.  

Thanks.

**Comment by ear-dev** [comment]
Here's a clue:
![image](https://user-images.githubusercontent.com/28864717/156062325-855fcd6b-9bc2-486e-85aa-dd9e6b76d5b8.png)

**Comment by ear-dev** [comment]
![image](https://user-images.githubusercontent.com/28864717/156063976-21f3aefb-57fa-4c69-a61a-8913a28bba7f.png)

**Comment by Shailesh351** [comment]
@ear-dev The issue is with invalid SF Configuration.
```
W20220301-07:36:10.048(5.5)? (STDERR) {"url":"https://c.la2-c2-ia5.salesforceliveagent.com/chat/rest/Chasitor/ChasitorInit","method":"post","statusCode":500,"headers":{"access-control-allow-credentials":"true","access-control-allow-origin":"*","cache-control":"no-cache","connection":"close","content-encoding":"gzip","content-length":"318","content-type":"application/json","expires":"-1","pragma":"no-cache"},"content":"An error has occurred while processing your request. The salesforce.com support team has been notified of the problem. If you believe you have additional information that may be of help in reproducing or correcting the error, please contact Salesforce Support. Please indicate the URL of the page you were requesting, any error id shown on this page as well as any other related information. We apologize for the inconvenience. Error ID: 795614101-2471 (-668829535)","data":null}
W20220301-07:36:11.607(5.5)? (STDERR) {"messages":[{"type":"ChatRequestFail","message":{"reason":"NoPost","attachedRecords":[]}}],"sequence":0}
W20220301-07:36:11.609(5.5)? (STDERR) Failed to handover {"errorMessage":"Entered app configurations are invalid. Please recheck.","dialogflow_SessionID":"phkPHjL94iT6RAr5A","salesforce_SessionTokens":{"id":"5de35cd3-fee0-421d-a149-aa959b2cbc79","affinityToken":"b8e51fa0","key":"5de35cd3-fee0-421d-a149-aa959b2cbc79!1646100365619!EVBV+GnH+aWnJmsab4qilYX3OlI="},"salesforce_OrganizationID":"00D4W000006ld8S","salesforce_ButtonID":"573P00000004H5F"}
```

The buttonId we pass in the handover payload should be proper. In the SF App, we have `Salesforce Chat Endpoint`, `Salesforce Organization ID`, `Salesforce Deployment ID`. and I think these all are connected
