### ISSUE TITLE
[logging] Prune RC logging to remove repetitive and useless log points globally

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1115]
Probably there is a large list of potential candidates?

- "Exception while invoking method roles/get 'Cannot read property 'find' of undefined'"
- "LivechatRoomClosedHandler {"rid":"FX7Mjxrsj5nCFSydB","appEventEndpointHttpRequest":{"data":{"action":"trigger-event","sessionId":"FX7Mjxrsj5nCFSydB","actionData":{"event":{"name":"end_live_chat","languageCode":"en"}}}}}"

I see those two alot in the error logging......  are they useful at all?
In the info and debug logging there are many, many, more...
I believe Shailesh had some ideas about how to go about this task.

**Comment by ear-dev** [comment]
@Shailesh351 I deployed the new RC server from this PR to our messaging.vega-dev.viasat.io instance, which is deployed into the 'test-messaging' namespace, which can be viewed in the preprod kibana.  It looks much cleaner, but there are a ton of log points with no message at all.  Any idea what those are?  Thanks. 

![image](https://user-images.githubusercontent.com/28864717/158648027-efb67052-0ffe-4da8-bc8e-813ca52cc348.png)

**Comment by Shailesh351** [comment]
@ear-dev That's strange. Looking into it 👍
