### ISSUE TITLE
[SF.app] Remove prechat-details from our handover process.  This should be completely the responsibility of fulfillment.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1119]
We will remove some hard coded stuff out of rocketchat and into Dialogflow.

When we get a handover payload, we should not parse or change the payload/transcript at all, but just forward the whole thing to salesforce. 

BLOCKED: DF.agent needs to include a few more custom_details(email, salesforceId, appVersion) in the df_perform_handover payload. to include the current prechat-details that are handled by RC.

```
prechatDetails: [
				{
					label: 'E-mail Address',
					value: LcVisitorEmail,
					entityFieldMaps: [
						{
							entityName: 'Contact',
							fieldName: 'Email',
							isFastFillable: false,
							isAutoQueryable: true,
							isExactMatchable: true,
						},
					],
					transcriptFields: ['c__EmailAddress'],
					displayToAgent: true,
				},
				{
					label: 'Case Id',
					value: salesforceId,
					entityMaps: [
						{
							entityName: 'Case',
							fieldName: 'ID',
						},
					],
					transcriptFields: [
						'CaseID',
					],
					displayToAgent: true,

				},
			],
```

**Comment by ear-dev** [comment]
Migration TODO: we want to be backwards compatible.  

- CX will implement a new df_perform_handoverv2 payload.
- This payload will include all the custom details and RC will not have to append anything. 
- RC needs to handle both flavors of df_perform_handover.

**Comment by ear-dev** [comment]
NOTE: we need a new payloadv2 definition to guarantee that we're all on the same page. @ear-dev talk to CX team about where to document and design.

**Comment by ear-dev** [comment]
NOTE for eric:  we need a new testbot test case for the new v2 version of the handover_payload

- CX team can reuse the current df_perform_handover payload, and they can add the new details, or not......  RC will detect and handle it properly.

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 what exactly has RC been responsible for in filling out prechatDetails?  Have we just been filling out the 'value' fields and sending the rest verbatim?  So it's just `salesforceId` and `lcVisitorEmail`?

**Comment by bhardwajaditya** [comment]
@ear-dev yes exactly. So payload is kind of constant apart from these fields

**Comment by ear-dev** [comment]
@Shailesh351 @bhardwajaditya it looks like these two PRs are ready to go?  I can merge them both and close the story?

**Comment by Shailesh351** [comment]
Yes @ear-dev It's ready to merge
