### ISSUE TITLE
[Print Chat][Web] redesign print chat to be 'save chat' on both web and mobile

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1121]
We would like to use the omnichannel feature "Ask Visitor if They Would Like a Transcript After Chat Closed" from the Admin/Omnichannel UI.  

Currently we have the 'print chat' feature visible in the 'options' section of the widget in web only, we want to remove that options menu entirely from web.

When the user finishes a chat, either by timeout or clicking the 'X', the 'Would you like to save your chat' prompt will appear after the "All of this conversation history will be lost if you close this chat. Continue?" prompt.  If the user selects 'Yes', we want the transcript saved to the local device, in both web and mobile.

Can we hook into the system level save functionality at this point?  Currently I think it's trying to send an email server side?

**Comment by ear-dev** [comment]
@AlexanderKanakis please include a log point for when visitors use the feature.

Feel free to download the file in whatever format is the **easiest to implement.**...  a new dependency to convert to pdf is fine if it works on both mobile and web.

**Comment by AlexanderKanakis** [comment]
Related PRs:

Rocket.Chat: https://github.com/WideChat/Rocket.Chat/pull/1130
Rocket.Chat.Livechat: https://github.com/WideChat/Rocket.Chat.Livechat/pull/130

**Comment by ear-dev** [comment]
@AlexanderKanakis please use the testApp to verify it works in an embedded environment.  

https://github.com/WideChat/Rocket.Chat.Livechat.Test-App/tree/sb_main

**Comment by ear-dev** [comment]
@AlexanderKanakis did you forget to remove the options menu on the lower left as part of this PR?  Otherwise it looks good.

**Comment by ear-dev** [comment]
@AlexanderKanakis there are two adjustments we would like to make to the save transcript design:

- Download as txt file (or pdf, or whatever is easiest, but not html please)
- We also want to replace the pop up modal that prompts for the download option, with a button, but ONLY in the escalated case when the visitor has been talking to a live agent in salesforce. 

@bhardwajaditya has a PR to provide a button for the feedback survey after a live agent session has closed.  We want to use the same button style for the download transcript button.  I think the best way to proceed is to wait until Aditya's PRs have been merged, then you can rebase against the latest and add the new print transcript button after that.  So please work on the html -> txt file part first.  Thanks...

![image](https://user-images.githubusercontent.com/28864717/163579043-23721cb6-7a7c-481f-ab7c-4cab7b012c1d.png)

@Shailesh351

**Comment by Shailesh351** [comment]
@AlexanderKanakis FYI Feedback Survey PR is merged in Livechat Repo. So you can now continue with `Save Chat` button

**Comment by ear-dev** [comment]
@AlexanderKanakis please prioritize the new button interface before completing the permissions issue on mobile.  It might be the case that we deploy this for web first. 

NOTE:  the Download Chat Transcript button will replace the modal entirely in both web and mobile

**Comment by ear-dev** [comment]
@Shailesh351 @AlexanderKanakis These PRs are working as designed for me now.  The button shows up when configured, and on web it downloads a txt file.  

@Shailesh351 can you test on mobile please, just to confirm that the button shows up properly after a chat is closed.  Also can you test on a build that includes the feedback survey and post an image here please of how the two buttons look together?

If it all looks good, I think the only thing missing is the permissions on mobile to actually download the file.  

Thanks!

**Comment by Shailesh351** [comment]
@ear-dev @AlexanderKanakis It's looking good on mobile as well. Here's the screenshot below.

Only pending items are
- Figure out a way to download the transcript on mobile.
- Change the format of the text content in the file.

Currently, it has unnecessary space at the beginning and keeping time at the end makes it look weird.
```
				Viasat Virtual Assistant  April 28, 2022 10:53 AM

				Test 15, Hi there! I am a virtual assistant, designed to answer questions about your service.

			
				You  April 28, 2022 10:53 AM

				Thanks!
```

we can have something like this
```
(April 21, 2022 11:05 AM) virtualassistant:
How can I help you?

(April 21, 2022 11:00 AM) you:
Noting. Thanks!
```

<img width="564" alt="Screenshot 2022-04-28 at 11 22 47 AM" src="https://user-images.githubusercontent.com/18264684/165691158-576abe1f-53e2-4cc0-b600-7824ae655a29.png">

**Comment by AlexanderKanakis** [comment]
@Shailesh351 New update is up: https://github.com/WideChat/Rocket.Chat/pull/1130

**Comment by ear-dev** [comment]
@Shailesh351 @AlexanderKanakis Thanks for getting this together.  I would like for Shailesh to demo this in our meeting today please, on both web and mobile if possible....  escalated / non-escalsted.

@AlexanderKanakis your latest commit fixes the file formatting?  If so, then we are ready to deploy this to production on web, but not mobile.  I would like to add an 'isMobile' switch to the Save Chat feature and hard code to not offer the Save Chat button until we have the permissions worked out.  This will allow us to deploy to production on web while we're working on it.  Thanks....

**Comment by AlexanderKanakis** [comment]
@ear-dev @Shailesh351 PR for disabling `Save Transcript` button for mobile: https://github.com/WideChat/Rocket.Chat.Livechat/pull/138
