### ISSUE TITLE
[Customer Survey] Navigate to the Customer Survey url within the widget after a session with live agent is closed.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1126]
The salesforce API now includes a postChatUrl attribute that we can use to redirect our visitors to the customer survey after a live agent chat has been closed. 

![image](https://user-images.githubusercontent.com/28864717/160173374-c69f936a-2cc1-4304-a36c-f56b19c10df2.png)

Full user journey designs will be available soon..... but....
- we need to insure that we end up back at the widget in all cases after the visitor is done with, or ignores, or leaves the survey in the middle. 
- we could also open the survey in a new window if that were somehow easier as a first iteration
- we probably need to offer a button somewhere, to the visitor after the chat has been closed, so they can choose to take the survey or not.

**Comment by ear-dev** [comment]
Question: How and when does the postChatUrl arrive?

Can we present text and a button at the end of a chat.  The button needs to trigger a link. 

- This is a change to the SF.app, where we send a final payload when closing a chat. 
- Need to verify that current livechat code can support link behind a button. 

Web:

- open a new tab. (then we're done, don't worry about it.)

Mobile:

- Open the survey link inside the webview as a new tab.  If the visitor x's out, then next navigation to the widget is the chat.  If the visitor closes or moves away from the mobile app, next visit to the widget shows the chat.  Test this!

**Comment by ear-dev** [comment]
current test survey page: https://viasat.az1.qualtrics.com/jfe/preview/SV_5u8rNKWJdqi5r5c?Q_CHL=preview&Q_SurveyVersionID=

**Comment by ear-dev** [comment]
@bhardwajaditya 
![image](https://user-images.githubusercontent.com/28864717/160656657-df3d55dc-b112-43bc-b05d-c762193b722c.png)

**Comment by ear-dev** [comment]
@bhardwajaditya Steve found this link for the salesforce API, and it includes some response body's with postChatUrl:  https://developer.salesforce.com/docs/atlas.en-us.live_agent_rest.meta/live_agent_rest/live_agent_rest_response_bodies.htm

Maybe that helps some?
Seems like it's contained in a few early responses we might have a handle on...

**Comment by ear-dev** [comment]
https://github.com/widechat/apps.salesforce.liveagent/blob/4fe5162ea6cda55aa1c3a2d2a338509d636708e1/handlers/InitiateSalesforceSessionHandler.ts#L146

That response will have the postChatUrl.......  :-)

**Comment by bhardwajaditya** [comment]
@ear-dev that's great it should solve what I was looking for . Thanks

**Comment by ear-dev** [comment]
@Shailesh351 can you review these PRs please... thanks
