### ISSUE TITLE
[SF.app] New admin entry for Conversation Finished Text in the escalated case.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1144]
Currently our conversation finished text is configured in Admin/Omnichannel/Livechat, and it is 'chat end'.  This shows up as a system message in the widget when a chat is closed. 

We need the ability to configure a different chat end message when we are coming from an escalated chat.  "Thank you for chatting with us.  How did we do today?", which will accompany the survey button. 

I'm not sure where the best place to put this is.  I think it's ok to have "end chat" in both cases, but maybe we need to add a system message configuration in the SF.app, so we can show both?  Thoughts?

**Comment by ear-dev** [comment]
NOTE: All system messages should appear above the Feedback Survey button.

**Comment by bhardwajaditya** [comment]
@ear-dev it will be better to add a livechat setting in the server to make it configurable. Something like "survey text" . This will be displayed in widget when survey is enabled otherwise normal close chat. Adding it to salesforce won't have much benefit and can make it a bit flaky as well

**Comment by ear-dev** [comment]
Thanks @Shailesh351 I'm good with that....  it's the livechat code that controls when the survey is to be displayed, based on escalated == true/false, right?  So it know.......

**Comment by ear-dev** [comment]
Admin/omnichannel/livechat

**Comment by ear-dev** [comment]
@Shailesh351 when you get a chance can you review please?  Unfortunately I don't have a testbed where I can do escalations, so please verify the feature.  Thanks.
