### ISSUE TITLE
[Two Tab issue] Verify that two or more tabs open to the widget are in sync in regard to the Feedback Survey.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1149]
Repro:
- tab1 escalates, agent closes the session, Feedback Survey button appears.  Minimize the widget.
- open tab2, talk to the DF bot and close the session without escalation.

Result:
- tab2 looks fine, chat is closed no Feedback Survey.
- tab1 the chat is closed, but the Feedback Survey button is showing.

**Comment by Shailesh351** [comment]
<img width="1481" alt="Screenshot 2022-04-21 at 8 32 55 PM" src="https://user-images.githubusercontent.com/18264684/164494055-d1ad9c2d-3e71-4829-99f6-0670aeb4e9a6.png">


Enabling `Clear guest session when chat end` fixes the issue

**Comment by ear-dev** [comment]
@Shailesh351 did you test various two tab scenarios with this setting enabled?  I just did and actually saw all kinds of weird behavior....  I need to look more carefully and characterize.....  but maybe if you have a minute you can also try a few things.  Thanks. 

I think what I saw was that closing a session in one tab caused the other tab to be orphaned and to show what I can only describe as 'undefined' behavior.... something like that....  but I'll look more closely as well..

**Comment by ear-dev** [comment]
Using this strategy also erased the setDepartment() value in the test widget, causing subsequent loads to use the default department. 

seems to me like we can't use this strategy.

**Comment by Shailesh351** [comment]
Okay @ear-dev I will fix it properly in the Live Chat repo👍

**Comment by Shailesh351** [comment]
NOTE: Created https://github.com/WideChat/Rocket.Chat/issues/1159 for the above pending issue
@ear-dev
