### ISSUE TITLE
[Test Widget] Add new fields for authentication against UsRes bot

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1162]
Two new input boxes in the test widget:
- "UsRes Account Number"
- "UsRes Zip Code"

These fields need to map to parameters we send to DF, in exactly the same way we send the phoneNumber as 'username'.

The mapping:
"UsRes Account Number" -> 'ui_register_account_number'
"UsRes Zip Code" -> 'ui_register_zip_code'

Notes:
- Only send these parameters in the case that the widget has provided the values.
- If no values provided send nothing for these parameters.
- These new values need to be cleared out in the case where the user does not explicitly set them in the testWidget. (i.e. in the phoneNumber case we have to add an unset method because the phoneNumber value gets stored in the mongodb.  In the case of our new values, maybe they are not stored in mongodb, so not an issue?  Not sure, but we need to verify.)

**Comment by AlexanderKanakis** [comment]
Related PRs:
https://github.com/WideChat/Rocket.Chat/pull/1173
https://github.com/WideChat/Rocket.Chat.IntegrationTests/pull/7

Custom fields in `{host}/omnichannel/customfields`:
1. `ui_register_zip_code`
2. `ui_register_account_number`

**Comment by ear-dev** [comment]
@AlexanderKanakis I am going to take a crack at this one please.... thanks.

**Comment by AlexanderKanakis** [comment]
I will be pushing new code as per Shailesh's changes very soon

**Comment by ear-dev** [comment]
@AlexanderKanakis @Shailesh351 I've got two PRs for this issue.  Shailesh can you confirm please if this implementation looks safe on the server side?  I basically mimicked using empty string from the phoneNumber PR, and passing customFields as a parameter from the appVersion PR. 

- https://github.com/WideChat/Rocket.Chat/pull/1183/files
- https://github.com/WideChat/Apps.Dialogflow/pull/155
- https://github.com/WideChat/Rocket.Chat.IntegrationTests/pull/8

I did test it end to end against our latest bot, and it is authenticating successfully.

**Comment by Shailesh351** [comment]
@ear-dev 

1. For the server PR, why do we need to unset the customField? I tested it when we pass empty from the widget it updates in the DB to empty? Do we specifically want to completely remove the property from the DB?
2. For the DF PR, We don't need to change anything to pass it in the Welcome Event. We are already sending a complete `livechatData` object (Visitor custom fields) in the welcome event.  https://github.com/WideChat/Apps.Dialogflow/blob/master/lib/payloadAction.ts#L152...L156

**Comment by ear-dev** [comment]
NOTE: EAR>>>  Do not need any of these PRs....  Visitor customFields by default are added as parameters in DF messages from inside the DF.app. 
TODO: Revert the appVersion PR from the DF repo:  https://github.com/WideChat/Apps.Dialogflow/pull/147/files
