### ISSUE TITLE
[Metrics Logging] Design and prototype a custom logger in RC server for publishing events to SNS

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1171]
We would like start tracking "frontend analytics" as described here:  https://wiki.viasat.com/display/ACC/Frontend+Analytics

We need a design document and a prototype if possible.  We can start by logging just one or two of the metrics described in the document.  

We will need to implement the schema requirements defined and provided by the fulfillment team.  They manage the SNS topics we will be publishing to.  

NOTE:  There may be some attributes required in the schema that we do not initially have access to in RC.  The 'partyID' is an example (it is used to identify a unique Viasat Customer, and is usually discovered by fulfillment during initial session setup, using the auth token (UsRes), or the phoneNumber (Brazil/whatsApp).

**Comment by ear-dev** [comment]
@Shailesh351 For a big picture view...  our Events/Metrics Service was originally described in this wiki:  https://wiki.viasat.com/pages/viewpage.action?pageId=549161101 Fred has implemented this and it is currently operational.  Our job is to push our metrics to that SNS topic he setup, and his service will take care of the rest.  

We just need to provide the databus schema information (described in the wiki) in json format as the message body in the SNS message we push to the topic. 

It looks to me like the only attribute we don't have a handle on is partyID.  However, Fred and I discussed maybe pushing to a dedicated RC topic without that value, and then the ciao service will know to go and get that value using the sessionID we provide in the message body.json.

**Comment by ear-dev** [comment]
Example event.json off the databus from our production stream:

```
{
"application": "WhatsApp",
"business": "BR",
"ciao_deployment": "brazil-prod",
"dialogflow_agent_id": "b5983b72-cac6-4f85-b9d0-be61e543dfe6",
"event": "outage_info_requested",
"event_detail_1": "none",
"event_detail_2": "none",
"event_detail_3": null,
"event_detail_4": null,
"event_type": "customer_action",
"party_id": "3a5bf619-6353-4412-a21b-bf2b1eab94db",
"session_id": "dfcx:b5983b72-cac6-4f85-b9d0-be61e543dfe6:wqbFXoeX2kdSZhSyi",
"source_component": "Ciao",
"timestamp": 1651688848191
}
```

**Comment by Shailesh351** [comment]
@ear-dev Here's the current document for Metrics Logging https://github.com/WideChat/Rocket.Chat/wiki/Pushing-Metrics-Events-Logs-to-SNS-for-Analytics
