### ISSUE TITLE
[SF.agent] Change the user icon to match the salesforce agents name.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1177]
We would like to use the first letter of the name, like the default RC username icon behavior.  This needs to be scoped specifically to just the current session, not a global change of the SF.app.bot username.

**Comment by ear-dev** [comment]
@bhardwajaditya please prioritize this one next when you are ready.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev I am picking this over the multi tab message issue, that one might take more time since just syncing messages across the tabs is introducing some new bugs. This one seems more straightforward

**Comment by ear-dev** [comment]
> @ear-dev I am picking this over the multi tab message issue, that one might take more time since just syncing messages across the tabs is introducing some new bugs. This one seems more straightforward

sounds good to me.....  thanks.
