### ISSUE TITLE
[SF.app][BUG] Sneak peek is flaky

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1184]

**Comment by Shailesh351** [comment]
NOTE: Check for multiple tabs scenarios

**Comment by ear-dev** [comment]
Related to 1203 maybe.....  could be a RestAPI vs. Websocket issue?

Websocket for realtime messages, will timeout eventually or go stale.  RestAPI used for getting history etc...

**Comment by ear-dev** [comment]
@bhardwajaditya can you please describe the issue you found with REST vs. WebSocket, and propose the fix here.  thanks?
