### ISSUE TITLE
[BUG] Visitor Custom Fields are not passing immediately after update in the Welcome Event

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1191]
When the custom field value is updated in the widget script, It is updated in the DB. But in the DF App, It still holds the older value and passes it to the DF Agent.

## Steps to reproduce
- Set customField in the Widget Script (i.e. value1)
- Start the chat and check if we are receiving it(value1) at DF Agent in the welcome event
- Change the value (i.e. value2)
- Start the new chat and check the value in the welcome event. **We are still receiving value1 here**
- Change the value (i.e. value3)
- Start the new chat and check the value in the welcome event. **We are still receiving value2 here**

So the issue is we are not receiving new value immediately. New value is being passed in the next turn.

**Comment by ear-dev** [comment]
@Shailesh351 is this just an issue for us when using our test widget, or is it possible this is something we might be seeing in production?  Is it possible this is related to our missing appName/token issues?  Are we sending the 'visitor' field values to DF.agent for those?

**Comment by Shailesh351** [comment]
@ear-dev Just with the test widgets.  (Where we try to update customFields like `this.setCustomField('ui_register_account_number', 'accno');`) 

I don't think there is any issue in production due to this. But still just to verify I will do some more testing for this

**Comment by ear-dev** [comment]
> I don't think there is any issue in production due to this. But still just to verify I will do some more testing for this

don't they use this.setCustomField to set appName and token?

**Comment by Shailesh351** [comment]
@ear-dev They do but this particular issue is when we try to update the value in the customField. In the MyViasat values just remain the same right?

**Comment by ear-dev** [comment]
I'm not sure if the token expires and refreshes.....  but in that case we'd be sending a stale token, not an empty token.... so likely not related.

**Comment by ear-dev** [comment]
@Shailesh351 perhaps the session you showed us in the meeting this morning is because of this issue?  You found a failed welcome intent that did have appName and token, but the transcript also included a bunch of old chat records.  Maybe this is an example of this issue where the token did not get updated and it was stale?

Can you add the roomID here so we can track please?

**Comment by ear-dev** [comment]
https://chatbot.vega.viasat.com/omnichannel/current/cE5vuwqSagN66faDD

**Comment by Shailesh351** [comment]
@ear-dev This issue is no longer reproducible in the latest develop branch. Maybe it got fixed with the upstream catchup. I will check the current develop_pwa branch 👍
