### ISSUE TITLE
[DF.app] Catchup merges

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1195]
We have diverged greatly from upstream so this might be a complicated merge.

**Comment by ear-dev** [comment]
@AlexanderKanakis please make no custom changes during the catchup merge PR.  Just merge them together but verify that all of our changes are still working.  

Any custom changes should be done in a new PR
- please create a story on the board about cleaning up our use of persistence.

**Comment by AlexanderKanakis** [comment]
PR: https://github.com/WideChat/Apps.Dialogflow/pull/159
Prettierrc: https://github.com/WideChat/Apps.Dialogflow/pull/166
