### ISSUE TITLE
[save transcript in mobile] Need an admin switch to enable/disable the feature

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1200]
We are going to be blocked on the MV PR which allows us to save the transcript on mobile.  This will prevent our other fixes from being promoted to prod, unless we have a switch to enable/disable on mobile. 

NOTE:  This may turn out to be a temporary fix for this issue, since we do not expect to use this after the new MyViasat eventually rolls out.  We may want to just revert the fix at some point later, since we would prefer not to add configurations that are unnecessary.

**Comment by AlexanderKanakis** [comment]
PRs: 
- https://github.com/WideChat/Rocket.Chat/pull/1201
- https://github.com/WideChat/Rocket.Chat.Livechat/pull/146

**Comment by ear-dev** [comment]
@AlexanderKanakis this works great.  Thanks....  @Shailesh351 can you take a quick look at these PRs please?  Thanks.
