### ISSUE TITLE
[SF.app][BUG] SF agent name in the banner and sneak peek is flaky when bouncing between websocket and REST

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1203]
When a live salesforce agent transfers the chat to another agent the name in the banner will also change with it.  However I'm seeing this as flaky, similar to how sneak peak is flaky.  

I'm testing with the sf_emulator

**Comment by ear-dev** [comment]
@bhardwajaditya since you are looking at the user icon in these cases, can you also take a look at this please?  For some reason the salesforce agent name in the banner generally is not robust.  I'm seeing this in the chat transfer case as well as the initial case when the visitor first escalates.  thanks.

**Comment by bhardwajaditya** [comment]
The root cause of the issue was that we were handling custom fields items such as sneak peek enable/disable and salesforce agent name in only messages received via web socket and not in messages received via rest api.

My PR has enabled to process these custom fields for both kind of messages
