### ISSUE TITLE
[SNS Logger] [Rocket.chat.js.sdk] Passes data over websocket from the Livechat Widget to the  Server/SNS SDK

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1207]

**Comment by ear-dev** [comment]
https://github.com/WideChat/Rocket.Chat/wiki/Pushing-Metrics-Events-Logs-to-SNS-for-Analytics

**Comment by ear-dev** [comment]
Please create any RC PR's for SNS work against sns_logger_master

**Comment by ear-dev** [comment]
@bhardwajaditya 
<p>Examples of the type of things we want to start tracking, and where the data comes from</p><p><br /></p>

  | Salesforce App | Rocket.chat | Frontend Client | Ciao
-- | -- | -- | -- | --
Did the agent close the chat? | X |   |   |  
Did the customer click on X or options -> Close chat? |   | ? | X |  
Did the customer close their tab? |   | ? | X |  
Did the customer download a transcript? |   | X | X |  
Was the customer transferred to another agent? | X |   |   |  
Did the customer wait in a queue? How long? | X |   |   |  
Did the customer timeout with agent? | X |   | X |  
Did the customer try to chat off-hours? | X |   |   | X
Button pushes? How many people click survey?(Probably exclude conversation buttons) |   |   | X |  
Clicking on links? |   |   | X |  
Room open / close / room timeout |   | X |   |  
Escalation failures | X |   |   |  
Empty app name / token |   |   | X | X
How often customer comes back |   |   |   | X - Pixel
Did Visitor Abandonment Timer close the session |   | x |   |  
Did the customer send an invalidUserInput |   | x |   |  
Did the customer open a duplicate tab  |   |   | x  |

**Comment by ear-dev** [comment]
@bhardwajaditya Please document here your design thinking around using REST vs. Websocket for this implementation. 
@Shailesh351 please comment on the proposed design so we can move forward with common concensus.

**Comment by bhardwajaditya** [comment]
I suggest to continue communicating from Widget to Server using REST APIs as it is currently used in all other communications in this direction. 

The other reason to use REST API is that they are not resource intensive, we will use the server as and when required and that doesn't require a persistent connection which drains server resources. We have a small subset of the cases when we will communicate with the server for sending the events so it will be better if we use it as and when required.

**Comment by Shailesh351** [comment]
@bhardwajaditya Using the REST endpoint for communicating sounds good to me as we are already using it for sending messages. My bad I didn't go into the details. Let's ensure we are implementing it similar to sending messages i.e using js SDK. Thank you for your suggestion!

**Comment by ear-dev** [comment]
NOTE: ear will provide event mapping for proper json payload contents.

**Comment by bhardwajaditya** [comment]
I have implemented the changes for all the events in the above mentioned list apart from the following three.

- Did the customer close their tab?
- Did the customer open a duplicate tab
- Empty app name / token

These three are part of this list but not part of excel sheet. @ear-dev can you confirm if these are required.

**Comment by ear-dev** [comment]
Good question @bhardwajaditya.  As you suggest, we have not covered tab behavior in the spreadsheet at the moment.  I'll discuss that with the chatbot team.  Empty app name / token might fall under a different category however, and not properly be considered as a customer event.... I'll verify. 

FYI - that spreadsheet describes specifically only events whose destination is Pixel, and that is where our stakeholders will have dashboards for analysis etc...  We will also be pushing our events to Druid, as an alternative destination for internal, developer analysis.  Therefore, some events we may send will be outside of the Pixel spreadsheet, but if we decide to send them to Druid, we'll want to use the same message payload format.  

So likely, we might add an event for Druid that would be {"category": "tab", "action": "close/open"}

**Comment by ear-dev** [comment]
@Shailesh351 I'm hoping that you can review these PRs......  and setup an end-to-end testbed that will demonstrate events going from the widget all the way through the system to an SNS topic.  I will also work on putting my own testbed together for this.

**Comment by Shailesh351** [comment]
@ear-dev Sure thing!

**Comment by ear-dev** [comment]
@bhardwajaditya please create a new PR against the SDK branch for your tabID interface.  We had previously merged what you were working on.

**Comment by ear-dev** [comment]
1. baditya.feature branch -> baditya.sns.branch (update SDK dependency)
2. baditya.sns_brangh -> WideChat
3. SDK PR
4. ServerPR - update the keys, Shailesh review
