### ISSUE TITLE
[Bug] Save Transcript is not working for a deployed server in Web

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1211]
When a user clicks on Save Transcript it opens URL `blob:https://messaging.vega-preprod.viasat.io/948d6627-4661-4b95-9aa2-60a3b9babe6f` and it's not a valid URL. However, It was working with localhost, So I could not find it during development.

<img width="1792" alt="Screenshot 2022-05-28 at 7 15 06 AM" src="https://user-images.githubusercontent.com/18264684/170807113-8e06d9e8-64b4-4108-a331-5cfd7e2eb914.png">

**Comment by Shailesh351** [comment]
Looks like it's only happening on my local setup. It's working on `https://messaging.vega-dev.viasat.io/livechat`. @ear-dev If you see this in PrePROD or PROD Please let me know.

**Comment by ear-dev** [comment]
Interesting.... I have tested this multiple times.... but I will check again. Thanks for the heads up.
