### ISSUE TITLE
[Save Transcript] Need to be backwards compatible during new MV.app rollout.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1213]
It may never be the case that users will all update the myViasat app.  We need to detect Save Transcript compatibility before presenting the 'Save Transcript' button to the user. 

- check for MV version?
- check for something else?
- maybe it's a method:  mobileEnableSaveTranscript() which can be called by the integration script.  Is the integration script the same on mobile as it is in web?

**Comment by ear-dev** [comment]
@AlexanderKanakis please come up with a design and then run it by the team before implementation.

**Comment by ear-dev** [comment]
@AlexanderKanakis @Shailesh351 Looks like we would like to prioritize this one.

 If our design includes changes to the MV app we can maybe make that the first task for @csmith14  in the myViasat repo.  

If we can get our MV changes committed by mid week next week, we might be able to make it in time for their next release.... fwiw.

**Comment by ear-dev** [comment]
NOTE: this will be like the hide show print option we created. 

Can we repurpose the current showPrint() hidePrint() methods that already exist in livechat for this purpose?   it would effectively be showSaveTranscriptButton() hideSaveTranscriptButton().... but we do not want to rename the methods at this point. 

Currently myViasat uses hidePrint() in mobile only.  showPrint() defaults to true.

**Comment by ear-dev** [comment]
NOTE: Currently in mobile, myViasat uses hidePrint() but in web they are falling back on the default showPrint().  If we hook this method into our new Save Transcript button logic, then we will effectively be backwards compatible.  

- Older versions of the myViasat app will have the hidePrint() method called.
- Newer (print compatible) versions of myViasat app will remove the hidePrint() condition.  We'll have to make a PR for that against the myViasat repo.

For now we will not make any changes to the current 'Allow Visitor to Print Transcript in Mobile' admin setting.  So we will effectively have two controls for this feature, but the hidePrint() method should override the admin setting.  We can make a future story to decide if we should eventually remove the admin setting. 

@AlexanderKanakis Let me know if this is not clear or if you have any questions.  Thanks...

**Comment by Shailesh351** [comment]
MyViasat PR for replacing `hidePrint` with `showPrint` https://git.viasat.com/ICAT/MyViasat/pull/1154
