### ISSUE TITLE
[RC upstream cypress tests] Fix tests so that they pass against our PWA fork

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1221]
Upstream has added a step in the github actions workflow that runs a suite of cypress tests.  Many of these tests are failing against our fork because of the PWA changes we have made.  

We need to comb through all the tests that are failing and fix, or comment out if not applicable somehow.

If you go through this log you can see the tests that are passing and failing....  https://github.com/WideChat/Rocket.Chat/runs/6575353939?check_suite_focus=true

**Comment by ear-dev** [comment]
@bhardwajaditya please enumerate our PWA changes that are the root causes of these failures.  Alexander needs to be more familiar with what our PWA refactor looked like, and what the effects here are.

**Comment by AlexanderKanakis** [comment]
PRs:
https://github.com/WideChat/Rocket.Chat/pull/1250
