### ISSUE TITLE
[SNS Logger][Refactor] Handle SNS topic endpoint, Region, Dialogflow_agent_ID to CX.agent mapping

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1226]
Each CX.agent represents a unique market (brazil, UsRes, Mexico, etc..), and therefore each sessionID (roomID) is mapped to a CX.agent/market as well.  This is already how the system works.  

New Design:
-  Each market will need to publish to it's own, unique SNS topic.
- We will need somewhere to configure the mapping of market -> SNS.topic
- Do we configure that in the CX.config.json?  or?

**Comment by ear-dev** [comment]
@Shailesh351 can you comment please on the best design for this?  We will need to incorporate this functionality into the RC.SNS.logger.  Thanks.

**Comment by Shailesh351** [comment]
@ear-dev Ideally the best place to configure it should be in DF config.json itself but that might make implementation more complicated i.e. Getting Topic ARN from DF App to Server, Also this will require more data to pass to identify the room and market/cx-agent and that means more DB lookups.

Give me some time to think of a way so that it does not make implementation complex

**Comment by ear-dev** [comment]
Thanks @Shailesh351 

We must already be handling a mapping between roomID and agentID, right?  I believe those are the minimum requirements that have to be included in every message so that ciao can do the partyID, business, etc queries on the backend, as we have discussed.  

This new requirement is to maintain a mapping of agentID to SNS topic.  And yeah, DF config.json seems best, but somehow upon agent initialization in DF.app we would need to pass that info back to the server.....  as you have suggested.  

It's not impossible that we could add an admin UI for the mapping.....  but that is a bit clumsy.  Thanks for thinking about it.

**Comment by ear-dev** [comment]
New value in config.json:   "sns_arn": "XXXXXX"

**Comment by ear-dev** [comment]
NOTE: refactor the current logger.

**Comment by ear-dev** [comment]
@Shailesh351 where are we on this?  I think we'll need to be able to configure the sns_arn from within the config.json before we can deploy to prod.  I'm going to move this into TODO

**Comment by Shailesh351** [comment]
@ear-dev We haven't started on this, but maybe it's time. This is a significant change because we will need to figure out how to do it efficiently by managing multiple SNS ARNs. Implementation with a single SNS ARN was straightforward.
