### ISSUE TITLE
[BUG] Livechat sometimes gets into a bad state where messages not appearing in the window.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1227]
Occassionally the widget does not show any messages.  The visitor can type, and the DF.agent will respond, but the window is blank.  I can see the conversation on the RC server, in the omnichannel/chats UI, but nothing is getting refreshed in the widget window.  A server restart will fix the issue. 

@bhardwajaditya have you ever seen this?  Any thoughts about why this might be happening?

**Comment by ear-dev** [comment]
NOTE: I might have a lead on why this is happening.  It seems to only be happening on the RC instances which are deployed into the preprod kubernetes cluster.  In preprod we do not have any reserved resources (memory, cpu, etc...) but in Prod we do.  This would put us in contention with other applications in the cluster that might be deployed on our shared Node. 

I have adjusted in Preprod so that we are reserving resources for our application, and we will monitor a week or so for the bad behavior before closing this issue.

**Comment by ear-dev** [comment]
Note: could be oplog issue with MongoDB?  ear will check resources and try a mongo restart next time.

**Comment by bhardwajaditya** [comment]
The following two links can be helpful in debugging this problem. There can be two possible problems, first one being a blocking method which stops all subsequent calls. We need to check meteor logs for that can be found using mup command in the running server. The second being DB being a bottleneck, explained in the second link mentioned below.

- https://forums.meteor.com/t/strange-phenomenon-subsequent-methods-or-subs-wont-succeed/55029/21
- [Users unable to log in with Meteor.loginWithPassword()](https://forums.meteor.com/t/users-unable-to-log-in-with-meteor-loginwithpassword/53056/3)

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 we got into this bad state again in preprod.  I did a restart of the mongodb service in the kluster but it did not resolve the issue.  :-(

I will look at the links posted above and think about next steps.  Thanks.

**Comment by ear-dev** [comment]
NOTE: we realized that our kubernetes resource limits for the mongodb pods were not reserved when we made this fix for the rocketchat server pods.  I have since included reserved resources on our dev server, but not on our preprod server.  We will be watching the servers for another repro.

**Comment by ear-dev** [comment]
We have not seen this issue since we increased limits on the mongodb pods.....  closing for now until it repros.
