### ISSUE TITLE
[Events] Can we track tab behavior

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1234]
- visitor opens a second tab. - DONE
- visitor switches tabs. - DONE because every event now includes tabID so we can track
- visitor closes a tab. - ??
- visitor closes a tab which closes the myViasat app. - ??
  - Note: myViasat app has more control and more information about tab behavior than we do....

**Comment by bhardwajaditya** [comment]
Added changes for opening a new tab, switching and closing tabs seems difficult requires some brainstorming
