### ISSUE TITLE
[scheduled events] Add the roomID to log points associated with scheduling events

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1239]
This will help us to debug issues we are seeing where scheduled events to not seem to be triggered in a timely fashion, or not triggered at all.

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 Do you think this might be a quick fix?  We did see a whole bunch of those events where the timer payload was not being scheduled or processed in a timely fashion again..... in Prod.  Restarting the RC server fixed the issue, but it will probably come up again and we need to figure out what's going on with this.  

Our logs will show when timer events get scheduled, but there is no roomID attached to the log point so it's not actually very useful yet.  If we can add roomID to any and all log points associated with the lifecycle of a scheduled task, it is my hope that that might help us debug?

**Comment by Shailesh351** [comment]
@ear-dev I just created two PRs for adding logs with data(rid).

Rocket.Chat:  https://github.com/WideChat/Rocket.Chat/pull/1240
Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/161
