### ISSUE TITLE
[Upstream Catchup] RC server

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1245]

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 

NOTE:  next catchup is a major refactor which moves to a "mono-repo"......  i.e. Livechat and Agenda will be moving into the RC.server repo.

**Comment by Shailesh351** [comment]
https://github.com/RocketChat/Rocket.Chat/releases/tag/4.7.2

https://github.com/RocketChat/Rocket.Chat/pull/25312

**Comment by ear-dev** [comment]
@bhardwajaditya we decided to roll back PWA changes......  can you believe it!!

Please do that first, and end up with a new base branch for us....  == develop.  Then go back to this catchup and do it against develop branch please.

**Comment by Shailesh351** [comment]
@bhardwajaditya @ear-dev

@bhardwajaditya Can you please make a list of the features which we will roll back? Just to make sure we don't lose anything important. I remember these three,
1. Push Notifications 
2. Sidebar changes for mobile 
3. Service worker changes for offline chat

**Comment by ear-dev** [comment]
Status: all 4.x merges are complete however livechat not functioning properly yet.  Aditya will debug, Shailesh can help. 

https://github.com/WideChat/Rocket.Chat/pull/1294

**Comment by ear-dev** [comment]
NOTE: the 4.x merges have been merged into develop...  next step to work on the 5.x merge.

**Comment by ear-dev** [comment]
NOTE: livechat filters and trigger still needs to be ported to "change streams", away from oplog.

**Comment by bhardwajaditya** [comment]
Server Branch - https://github.com/WideChat/Rocket.Chat/pull/1341
Apps Engine - https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/55
