### ISSUE TITLE
[pwa rollback] remove PWA changes - new base branch == develop?

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1267]
- Force push develop_pwa -> develop
- Roll back PWA changes in the develop branch (PR)
- After that we have a new base branch == develop

- The new catchup merge goes against our new develop base branch.

**Comment by Shailesh351** [comment]
@bhardwajaditya @ear-dev

@bhardwajaditya Can you please make a list of the features which we will roll back? Just to make sure we don't lose anything important. I remember these three,
1. Push Notifications 
2. Sidebar changes for mobile 
3. Service worker changes for offline chat

**Comment by bhardwajaditya** [comment]
Changes rolled back:

1. Push Notifications
2. Sidebar changes
3. Service worker registration
4. Local storage of ownUser, Chat messages, Roles
5. Lazy loading of emoji module
6. Css changes for PWA
7. Read receipts
8. Message popup changes
9. Offline message actions/file upload
10. Search bar designed for PWA
11. Removal of manifest file

**Comment by ear-dev** [comment]
@bhardwajaditya please include the removal of those new features Shailesh pointed out, because we do not need them anymore and want to get as clean as possible in preparation for the v5.x refactor merge.

**Comment by ear-dev** [comment]
Process: 

- merge this into develop when ready
- create PRs for all of the 4.x catchup merges against the new develop, and when ready we'll merge that into develop
- create PR for the v5.x refactor merge against the clean and fully up to date develop branch.

**Comment by ear-dev** [comment]
this is ready to be tested.  @ear-dev will test.  @Shailesh351 will give it a final review.
