### ISSUE TITLE
[SNS Logger] Add MessageGroupId to the metadata in our events sent to SNS.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1276]
See:  https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Client.publish

We need to include another parameter on the same level as 'Subject' for 'MessageGroupId'.  For now we will associate our message group with the specific RC instance sending the message.  Therefore each Rocketchat Server will have a unique MessageGroupId that will be attached to all messages coming from that server. 

Maybe we can use the 'Site Name' or the Site Url, as it appears in the Admin/General UI.  Just need make sure it is formatted to fit the alpha numeric constraints described in the link above.

**Comment by Shailesh351** [comment]
@ear-dev I have added Site URL as MessageGroupId in this PR https://github.com/WideChat/Rocket.Chat/pull/1228
