### ISSUE TITLE
[BUG] [Chat End Logging] Fix "Conversation closed:" logging as seen in a chat session transcript for escalated sessions

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1278]
Currently the "Conversation closed" message is not always accurate.  

For example, in an escalated session all Conversation closed messages show "Chat ended by visitor", even if the chat was actually closed by the agent, or timed out. 
https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/master/helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts#L62

We need to properly define all the reasons while closing rooom. visitor, agent, session expired etc.  We should verify for both escalated and non escalated sessions. 

As a side note: our SNS event logging for chat closed needs to be accurate as well...

**Comment by ear-dev** [comment]
Non Escalated Sessions:  I'll make a new story for these

- visitor abandonment
- closed by visitor (clicking the x)

**Comment by AlexanderKanakis** [comment]
PR: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/75

**Comment by ear-dev** [comment]
Reopening:  After deploying this into production our escalation numbers got worse.... i.e. attempted + successful + failed do not add up at all.  Before this upgrade they were very close, within 1 - 5 diff.

Here's how it looks now, in the past hour since doing the upgrade. 

![image](https://user-images.githubusercontent.com/28864717/195886656-e91e8312-e3a2-46e6-88c2-0c2020f078f6.png)

**Comment by ear-dev** [comment]
@Shailesh351 will look at this to see what we may have broken.

**Comment by ear-dev** [comment]
@AlexanderKanakis FYI - we had to revert this PR out of the main branch in the SF app.  It's still unclear exactly what was happening, it could have been simply that I was experiencing a bad install on our prod instance.  In any case, we're testing again now, and we can merge it back in when ready. 

NOTE:  One thing I am seeing at the moment on this branch is that failed escalations are getting logged twice at times.....  still testing to verify.

**Comment by ear-dev** [comment]
@Shailesh351 will add a fix for double logging of agent not available event.  Maybe the issue we saw in prod was a bad installation and ear will test again in preprod
