### ISSUE TITLE
[SNS Logger] Add events from Dialogflow app

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1279]
Our source of truth in regard to the list of events we want to implement is here: https://github.com/WideChat/Rocket.Chat/wiki/SNS-Logger

This story for Dialogflow events in particular:
```
{
  "Chat Session": [
       {"started": [{}]} <- DF.app
  ],

  "Escalation": [
  	{"attempted": []}, <- DF.app?
  	{"failed": [
  		{"failure_reason": "outside service hours"}, <- DF.app? - currently not available TODO later.
  		{"failure_reason": "network/app error"} <- DF.app?
	]},
  ]
 }
```

**Comment by Shailesh351** [comment]
@ear-dev I have added some events below which I indentified in the code.
```
{
  "Chat Session": [
       {"started": [{}]} <- DF.app
  ],

  "Escalation": [
  	{"attempted": []}, <- DF.app?
  	{"failed": [
  		{"failure_reason": "outside service hours"}, <- DF.app? - currently not available TODO later.
  		{"failure_reason": "network/app error"} <- DF.app?
  		{"failure_reason": "invalid target department"} <- DF.app? (Added by Shailesh)
  		{"failure_reason": "same target department"} <- DF.app? (Added by Shailesh)
  		{"failure_reason": "liveagent bot offline or disabled"} <- DF.app? (Added by Shailesh)
	]},
  ]
 }
```

**Comment by ear-dev** [comment]
@Shailesh351 we just confirmed with the Pixel team that it is fine to add new property values at will.  I just need to add them to that tracking-plan.xls.  So feel free to add those new values you are suggesting please.  Same thing in the SF story as well of course. 

Note:  we have sometimes been seeing both "same target department" and "liveagent bot offline or disabled" and perhaps we should try to debug those.  I'll make a story.

FYI - I also updated our master list in the wiki with these new values.
