### ISSUE TITLE
[BUG][SF] agentEndedFlag is true when chat ended by visitor

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1282]
When chat is ended by Salesforce Agent, it sets a flag in customFields `agentEndedFlag` to true.
But currently, it is also setting a flag in the case when the visitor ends the chat, which is misleading.

For now to differentiate chat ended by visitor and agent we can check `Conversation closed:` reason in RC .
It shows `Chat closed by visitor..` when the agent closes the chat.
It shows `Closed by visitor.` when the visitor closes the chat
We are going to fix this confusion separately in https://github.com/WideChat/Rocket.Chat/issues/1278

FYI @ear-dev

**Comment by ear-dev** [comment]
@Shailesh351 Are you saying that currently when the visitor ends the chat, the same `agentEndedFlag` is set to true?  So that flag is always set to true regardless of who closes the chat?

**Comment by Shailesh351** [comment]
> @Shailesh351 Are you saying that currently when the visitor ends the chat, the same `agentEndedFlag` is set to true?  So that flag is always set to true regardless of who closes the chat?

Yess

**Comment by ear-dev** [comment]
> > @Shailesh351 Are you saying that currently when the visitor ends the chat, the same `agentEndedFlag` is set to true?  So that flag is always set to true regardless of who closes the chat?
> 
> Yess

Wow.......  good catch!  thanks.
