### ISSUE TITLE
[SF logging] Implement a timer that will track queue_time while a visitor is waiting to be connected to a live agent.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1286]
There does not seem to be any value for this coming from SF itself.  We would like to be able to track queue_time in the handover successful event.

**Comment by ear-dev** [comment]
SNS logger events wiki:  https://github.com/WideChat/Rocket.Chat/wiki/SNS-Logger

**Comment by AlexanderKanakis** [comment]
PR:
https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/74
