### ISSUE TITLE
[BUG] Blackout window does not work after first message in a new session

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1287]
We are seeing sessions where the visitor types "hello" and then immediately types something else like "1".  In these cases both messages are getting through to CX.agent, before the agent has time to respond to the initial message. This causes the agent to throw one of those "no handler is defined for" errors. 

Is it possible that the DF message that includes the 'disableInput' customField at session startup is killing the blackout window?

example session:  https://ba.chatbot.vega.viasat.com/live/g9W3uhvLi6R5hhshB

NOTE:  I will enable debug logging in Prod Brazil until we catch a few of these so we can get a better view of the scheduled task lifecycle.

**Comment by Shailesh351** [comment]
```verificationPause -> Text and event RegisteredAccountInfo(User sends msg in between which is queued) -> queue msg sent and verificationPause received again -> now RegisteredAccountInfo executed which throws no handler error```

Example sessions: Brazil PROD rXwMHDbHgcu4wmGYk wyLPPDeEGXFkEZoTw

https://github.com/WideChat/Apps.Dialogflow/commit/db91d5566cb58b0a979ea65d40a108054484fe32
https://github.com/WideChat/Apps.Dialogflow/pull/145

@ear-dev

**Comment by ear-dev** [comment]
solution:  DF.agent should include a 'drop_queue' action along with the verification_pause (timer_event == verification_pause)

**Comment by ear-dev** [comment]
NOTE: We think that we missed a requirement in the spec for blackout_window and queue_window:

- Blackout window and queue window are mutually EXCLUSIVE. They cannot exist at the same time.  Blackout window ALWAYS takes precedence over a queue window.

Once we implement this then we will not be sending that rogue message off the queue at the end of our blackout window, which was the cause of the DF.agent errors.

**Comment by ear-dev** [comment]
@Shailesh351 should this be "under review" now?  Thanks.
