### ISSUE TITLE
[BUG][chat window] Double New line characters are collapsed to a single new line in RC livechat chat windows.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1288]
We would like to be able to send messages from DF.agent that were formatted with new line characters.  Currently when those are displayed in the widget the new line character is stripped and the lines are collapsed. 

Same as described in this issue:  https://github.com/RocketChat/feature-requests/issues/385

**Comment by ear-dev** [comment]
if the server is collapsing then the change will be on the server and not in livechat.....  it just get picked up in our widget.

**Comment by AlexanderKanakis** [comment]
PR: https://github.com/WideChat/Rocket.Chat.Livechat/pull/153
