### ISSUE TITLE
[Chat End Logging] DF.app proper chat end reason logging; Failed escalations (DF.app and SF.app)

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1297]
This story is for system messages only. i.e. messages that the visitor does not see, but they appear in the Admin/Ui as "Conversation closed" messaging.  We need to make sure all the conversation closed messaging is accurate. 

DF.app:
- visitor abandonment
- chat closed by visitor (clicking the x)
- SF service unavailable (dept. not configured)
- ??

SF.app:
- service unavailable
- no agents available
- ??

**Comment by AlexanderKanakis** [comment]
PRs:

Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/172
Apps.Salesforce.LiveAgent: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/78

**Comment by ear-dev** [comment]
Since I have merged the DF PR, and @AlexanderKanakis is going to combine PR 78 into SF PR 75, I am going to close this story, and then we will have a single story in regard to the close chat messages in the SF repo.
