### ISSUE TITLE
[BUG] [Duplicate of 1297] - Conversation closed message contains the a DF.config value for "close_chat_message"

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1298]
The DF.config value for "close_chat_message" should appear in the transcript window.  

Our bug is that when we hit the "invalid department" error during escalation,  it is currently showing up in the "Conversaion closed:" system messages.

**Comment by AlexanderKanakis** [comment]
PRs:

Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/172
Apps.Salesforce.LiveAgent: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/78
