### ISSUE TITLE
remove unneeded pieces from account/profile page

### ISSUE THREAD

**Issue by jaytat0** [WideChat/Rocket.Chat#13]
The below are widechat-only changes to be made on the web client profile page. (Note: there are still some details to be worked out regarding Delete My Account, but we will cover those separately.) We should continue the convention in use in the widechat android repo of putting these widechat-only changes under the "// WIDECHAT" flag.

	•	remove new password field
	•	remove name field
	•	remove "Your Rocket.Chat administrator has disabled the changing of [x]" language when fields are disabled/greyed out.

**Comment by ubarsaiyan** [comment]
@jaytat0 

- So, these changes are to be made in the WideChat fork right?
- These are not to be made configurable, only to be deleted?
- And sorry, I don't know about the convention of "// WIDECHAT" flag. Can you please elaborate?

**Comment by jaytat0** [comment]
- Correct
- Correct
- This is a flag we've been using in the android client repo to help with merges. It isolates widechat-only code. You can see an example in this pr and if you search in the repo you can see it in a lot of places: https://github.com/WideChat/Rocket.Chat.Android/pull/170/files#diff-c87ddf9f72caeda00164d1a1c8fbf202R80
