### ISSUE TITLE
[SF.app] Design and implement dynamic Salesforce URL site switching

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1302]
We recently had an issue where we failed to escalate sessions because Salesforce itself did an update and switched our site URL without notifying us.  That is apparently normal Salesforce behavior, and part of their normal failover/maintenance. Here is an article about it, as well as how we are supposed to handle it:
 
https://help.salesforce.com/s/articleView?id=000337828&type=1
https://help.salesforce.com/s/articleView?id=000336101&type=1
 
TDLR: There’s an API endpoint we can hit that will send us a “SwitchServer” payload if we are using the wrong URL, that contains the new URL that we should be using:
 
https://developer.salesforce.com/docs/atlas.en-us.live_agent_rest.meta/live_agent_rest/live_agent_rest_implement_chat_visitor_experience_requests.htm
 
We need to design how we can use this endpoint to automatically identify, and update our SF site url in the case that it has changed.  We do expect this to happen at least a couple of times a year if not more frequently.

**Comment by csmith14** [comment]
After some research, it looks like the only endpoint that returns this 'SwitchServer' payload is `/chat/rest/Visitor/Availability`

Forum post on the topic:
https://developer.salesforce.com/forums/?id=9060G000000UVwHQAW

Availability Endpoint doc:
https://developer.salesforce.com/docs/atlas.en-us.live_agent_rest.meta/live_agent_rest/live_agent_rest_Availability.htm

SwitchServer response doc:
https://developer.salesforce.com/docs/atlas.en-us.live_agent_rest.meta/live_agent_rest/live_agent_rest_response_bodies.htm#SwitchServer

**Comment by Shailesh351** [comment]
@csmith14 @ear-dev How about calling `/Availabilty` endpoint before sending a chat request to Salesforce?

I checked from the RC side, there is no direct method to update the App setting from the code. It only supports updating the App settings from the App at the initialization stage https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/accessors_isettingsextend.isettingsextend.html.

Still, if we can integrate the `/Availabilty` endpoint we can log errors for `SwitchServer` and get alerts at the moment. until we figure out whether to update the setting at runtime or a way to use a new endpoint.

**Comment by csmith14** [comment]
It seems that we do hit this endpoint already [here](https://github.com/WideChat/apps.salesforce.liveagent/blob/0380e65f8fc0c677de806a9ff600083d5db5f39d/endpoints/AvailabilityEndpoint.ts#L55)

But I'm not sure if we could extend it to return the new url in the `results` property of the returned object? And if we did, what the result of that would be is unclear as I haven't looked closely at how that [`extendConfiguration` hook is used](https://github.com/WideChat/apps.salesforce.liveagent/blob/0380e65f8fc0c677de806a9ff600083d5db5f39d/SalesforceLiveAgentApp.ts#L125)

**Comment by Shailesh351** [comment]
> It seems that we do hit this endpoint already [here](https://github.com/WideChat/apps.salesforce.liveagent/blob/0380e65f8fc0c677de806a9ff600083d5db5f39d/endpoints/AvailabilityEndpoint.ts#L55)
> 
> But I'm not sure if we could extend it to return the new url in the `results` property of the returned object? And if we did, what the result of that would be is unclear as I haven't looked closely at how that [`extendConfiguration` hook is used](https://github.com/WideChat/apps.salesforce.liveagent/blob/0380e65f8fc0c677de806a9ff600083d5db5f39d/SalesforceLiveAgentApp.ts#L125)

Yes that endpoint is currently just sitting there as exposed App REST API endpoint https://github.com/WideChat/Apps.Salesforce.LiveAgent/tree/master#rest-api-endpoints

But it is not part of the chat creation flow.

One other option is to periodically call the above endpoint and also use REST API to update the App setting. Not a good option though as we will need to maintain it separately

**Comment by ear-dev** [comment]
We have been notified that there will be another SF site switch in November.  If we could implement this before then that would be very useful I think.

**Comment by ear-dev** [comment]
Design:  Check availability endpoint before every new session with SF.  If url has changed, set a flag and store the new URL for the entirety of the session.  Throw a RC ERROR log point indicating the site switch, including the new URL, and we will alert on that and change the Admin setting to use the new url.
