### ISSUE TITLE
[SNS logging] Add event for visitor abandonment.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1304]
When the visitor closes the tab mid session, the chat close functionality belongs to Visitor Abandonment.  We would like an RC event for this. 

Added this to the wiki.

**Comment by ear-dev** [comment]
@Shailesh351 maybe this will be a quick one?  We're thinking that this might account for the discrepancy in our "total sessions" vs. "session close method" event tracking. Thanks.

**Comment by ear-dev** [comment]
@Shailesh351 I merged this PR, but then noticed that it was against the develop branch.  Can you recreate the PR against the develop_pwa branch please?  thanks.

**Comment by Shailesh351** [comment]
@ear-dev I forgot to create it against develop_pwa. Sorry about that. I have created a new PR for develop_pwa https://github.com/WideChat/Rocket.Chat/pull/1320
