### ISSUE TITLE
[Bug][Widget Timeout][Escalated Sessions] Disable the close chat functionality in the widget when timeout control is set by the SF.app

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1305]
We still want to show the timeout timer banner on the widget, so we will need to continue sending the customFields from the SF.app.
We will rely only on the scheduled event currently being set by the SF.app when it is set to "App"

**Comment by csmith14** [comment]
This has been addressed in this PR: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/79
