### ISSUE TITLE
[RC API] Fix the users endpoint to conform to standards when updating (PUT) a user

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1312]
The body of a POST request to the users endpoint looks like this: 
```
{
  "username": "${agent_username}",
  "email": "${agent_email}",
  "password": "${agent_password}",
  "name": "${agent_name}",
  "roles": ["bot", "livechat-agent"],
  "active": true,
  "status": "online"
}
```

But the body of the PUT request on the users endpoint is nested like this: 

```
{"data": 
    "user": {
        "username": "${agent_username}",
        "email": "${agent_email}",
        "password": "${agent_password}",
        "name": "${agent_name}",
        "roles": ["bot", "livechat-agent"],
        "active": true,
       "status": "online"
    }
}
```

This is a problem in our automation because we can only support a single template file for the body of an API request. 

Can we modify the put request to handle the un-nested payload?

**Comment by AlexanderKanakis** [comment]
@ear-dev are you sure that the current body has this form?
```
{
   "data": {
      "user": {}
   }
}
```

I sent a PUT request with this body successfully:
```
{
   "data": { }
}
```

**Comment by ear-dev** [comment]
{"data": { "user": {}}} worked for me, maybe it works for both?

But in any case, is it possible to factor such that we don't need the "data" block?

**Comment by AlexanderKanakis** [comment]
@ear-dev I have successfully modified the PUT method of `users/:userId` but we also have a POST method with `users.update/:userId`. Do we want to alter it too?

**Comment by ear-dev** [comment]
nope.  that users.update endpoint is the legacy endpoint from upstream, and we do not want to use those.  thanks.
