### ISSUE TITLE
[BUG] Character handling is not correct in the RC Admin UI view, or in Salesforce

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1321]
We recently fixed special character handling in the message parser as it appears in the widget.  Currently that part looks good.  But if you look at the RC Admin UI and view a conversation, the special characters are mangled.  It also shows up that way in Salesforce, which we definitely need to fix. 

Our recent fix:  https://github.com/WideChat/Rocket.Chat/issues/1308

View in the Widget:

![image](https://user-images.githubusercontent.com/28864717/195162005-bb08a7cc-b228-495c-bf3e-e4e7a45be23a.png)

View in RC UI:

![image](https://user-images.githubusercontent.com/28864717/195161753-69de56fc-11c5-49d2-8a5c-d7b447b41124.png)

View in Salesforce: 

![image](https://user-images.githubusercontent.com/28864717/195161830-c693b0f9-5f63-4931-9cb6-cbd112ac8cee.png)

**Comment by AlexanderKanakis** [comment]
![image](https://user-images.githubusercontent.com/18405180/196435351-32c11711-923b-494b-b412-ffb9031a7688.png)
SF view

**Comment by ear-dev** [comment]
@AlexanderKanakis please revert the livechat changes we made in our initial fix for this issue and attach the PR to this story.  Thanks.

**Comment by ear-dev** [comment]
> @AlexanderKanakis please revert the livechat changes we made in our initial fix for this issue and attach the PR to this story. Thanks.

@AlexanderKanakis did you also do this and test?

**Comment by AlexanderKanakis** [comment]
https://github.com/WideChat/Rocket.Chat.Livechat/pull/156. Tested.
