### ISSUE TITLE
[SF.App] Error the message already contains a custom field by the key: salesforceAgentName\

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1324]
We are seeing error in the SF app while adding custom field `salesforceAgentName `

```
[
  "{\"stack\":\"Error: The message already contains a custom field by the key: salesforceAgentName\\n    at MessageExtender.addCustomField (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/accessors/MessageExtender.js:19:19)\\n    at Ts.exec (evalmachine.<anonymous>:1:48825)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\\n    at Ys.executePostMessageSent (evalmachine.<anonymous>:1:72198)\",\"message\":\"The message already contains a custom field by the key: salesforceAgentName\"}"
]
```

**Comment by ear-dev** [comment]
@Shailesh351 please add some info and links to this story to point alexander to the issue.  thanks.

**Comment by Shailesh351** [comment]
We are seeing this after this PR. Maybe it is because we are setting salesforceAgentName in `helperFunctions/LivechatMessageHelpers.ts` but we didn't remove it from `lib/PostMessageClassInitiateHandler.ts`

**Comment by AlexanderKanakis** [comment]
> We are seeing this after this PR. Maybe it is because we are setting salesforceAgentName in `helperFunctions/LivechatMessageHelpers.ts` but we didn't remove it from `lib/PostMessageClassInitiateHandler.ts`

Any specific PR?

**Comment by Shailesh351** [comment]
Sorry, I forgot to mention. Here's the PR https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/67
