### ISSUE TITLE
[Upstream Catchup] Fix Issues found after the latest RC Server catchup 4.8.1

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1329]
- [ ] Build is failing
- [x] Last updated commit hash UI changed
- [x] Merge conflicts in history.json file
- [x] We removed all the cypress tests?
- [x] Some Localizations are not needed anymore. Need to be removed I.e. Vapid_public_key
- [x] Duplicate key in the pt-Br.i18n.json file
- [x] Contacts/server is back. I think we removed it
- [x] Some push notifications and push Message UI related stuff is back
- [x] Why Template.instance() -> Template.currentData() changes in actionButton.ts files?
- [x] share.css is back

**Comment by Shailesh351** [comment]
@ear-dev @bhardwajaditya I successfully ran the latest catchup(https://github.com/WideChat/Rocket.Chat/pull/1294) locally. Functionally all looks good. But I did find some other issues. I have mentioned those in this Issue. Thanks!

**Comment by ear-dev** [comment]
thanks @Shailesh351 "Auto catchup is disabled" I think you are referring to the fact that I disabled it intentionally?  My thought is that we don't want to run that now, until we have finished with the 5.x catchup stuff and we're all caught up that far.  I think that's the right thing to do?

**Comment by Shailesh351** [comment]
> thanks @Shailesh351 "Auto catchup is disabled" I think you are referring to the fact that I disabled it intentionally? My thought is that we don't want to run that now, until we have finished with the 5.x catchup stuff and we're all caught up that far. I think that's the right thing to do?

Yeah, If we did it intentionally then it's fine. Just need to make sure we don't forget to enable it 😄 . Maybe we can create an issue for that?

**Comment by ear-dev** [comment]
@Shailesh351 @bhardwajaditya Lets have Shailesh fix these remaining issues against the develop branch, and get the 4.8 version exactly how we want it before merging a 5.x branch.  That will allow Aditya to keep working on the 5.x stuff.  Thanks.

**Comment by ear-dev** [comment]
This PR passed all the testbot test cases and we merged it.  However we are still failing the build workflow.  I'm going to close this one and open a new story to track our build issues.  We will need to figure this out, but it should not block the catchup work moving forward.  @Shailesh351 @bhardwajaditya
