### ISSUE TITLE
[BUG][Livechat Widget] Avatar not showing up proper in the widget when SF liveagent is typing

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#1330]
When Salesforce liveagent is typing, an avatar is not the agent name initial, it’s the RC liveagent user avatar

<img width="758" alt="Screenshot 2022-10-20 at 7 05 14 PM" src="https://user-images.githubusercontent.com/18264684/196983119-c0fa2dd6-b364-4d9d-a40e-bb91b8c13c96.png">

**Comment by ear-dev** [comment]
@bhardwajaditya should I assume then that you did reproduce the issue on the 5.x branch before the fix?

**Comment by bhardwajaditya** [comment]
@ear-dev yes, I was looking into wrong place I
Thought banner was the issue, but it was avatar beside the agent name.
