### ISSUE TITLE
[Bug] Fix develop branch build issues.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1339]
https://github.com/WideChat/Rocket.Chat/actions/runs/3439542852/jobs/5773181025

**Comment by ear-dev** [comment]
**Status:**  If we use the yarn --debug flag, our builds will work.  We think that has to do with parallelization / memory, but there also might be issues with dependency versions. 

For now we will use the --debug flag, but we should keep exploring to figure out how to make a "real" fix?

**Comment by Shailesh351** [comment]
@ear-dev @bhardwajaditya It's strange! when I pushed the same develop branch on my fork(https://github.com/Shailesh351/Rocket.Chat), the build was successful https://github.com/Shailesh351/Rocket.Chat/actions/runs/3576028397

**Comment by bhardwajaditya** [comment]
@Shailesh351 we have updated the debug flag in develop. The code you pushed is with debug flag or without it?

**Comment by Shailesh351** [comment]
Ohh sorry! I pushed changes as it is. I will try again with removing the flag 👍

**Comment by ear-dev** [comment]
Status: it might be the case that switching develop to our default branch will fix the build issues.... testing now

**Comment by ear-dev** [comment]
@Shailesh351 I tested this on the develop branch and it works!  Nice find!

https://github.com/WideChat/Rocket.Chat/actions/runs/3631625118

Did you want to look at anything else, or can we close this story now?
