### ISSUE TITLE
[catchup] find agenda changes and include in mono-repo

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1345]
Shailesh can point to the PR/changes needed.

https://github.com/RocketChat/agenda/compare/master...WideChat:agenda:master

**Comment by ear-dev** [comment]
https://github.com/RocketChat/agenda/commit/98a45dcd0694e03a87a1027672307bc670ea2698

**Comment by bhardwajaditya** [comment]
@ear-dev I have verified these changes are there in our catchup from upstream, we can close this issue.

**Comment by ear-dev** [comment]
thanks @bhardwajaditya
