### ISSUE TITLE
[5.1 Bugs] Fix list of issues in this story

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1357]
1. ~~Please document the configurations required to use change streams in our infrastructure.  Currently we deploy with the helm chart and it is defaulting to oplog.~~
2. ~~Fix failing cypress test in the build:  seems to be a bad external url used for testing 'url preview' in a message? - under test~~
3. ~~Remove the options button in the widget. - under test~~
4. Visitor Abandonment does not seem to kick in after the first message from the welcome intent.  This used to work.  Now it only kicks in after a second message from the bot. - needs investigation in mongodb (ear)

**Comment by ear-dev** [comment]
@bhardwajaditya please add any info you have on the Visitor Abandonment issue here.  Where should I look in the db for the value that should be set, etc...  Thanks!  I can try to debug.

**Comment by bhardwajaditya** [comment]
@ear-dev check for the field `omnichannel.predictedVisitorAbandonmentAt` in rocketchat_rooms collection. This value is used to determine when to close the room which are abandoned.

**Comment by ear-dev** [comment]
@bhardwajaditya I checked it out, and yes, I can confirm that upon the initial message from our bot, the predictedVistorAbandonmentAt key is NOT present in the db.  After the visitor responds to the bot, and the bot responds to the visitor, that value is added to the room object in the db.

**Comment by ear-dev** [comment]
@bhardwajaditya 
After escalation, conversations with the liveagent look weird. After every message from the live agent, the agent typing indicator goes off, and the liveagent avatar becomes doubled, then tripled, etc...

can you verify what it looks like when you are talking to a liveagent?  Thanks.

This is what it looks like, even after the session had timed out:

![image](https://user-images.githubusercontent.com/28864717/218833116-adb0716f-0a93-45df-8de0-8d16c1608e41.png)

**Comment by ear-dev** [comment]
Another example against the real Salesforce instance in preprod...  of note, the avatar that is stuck showing the agent typing is for V and not the agents name E

![image](https://user-images.githubusercontent.com/28864717/218834429-f2738dc7-1b44-4c39-a65c-1904caf75c2b.png)

**Comment by ear-dev** [comment]
Status: 

- We need to revert the agent typing fix we made in the RC repo. 
- In the SF.app repo, we need to pass the agent name to the typing indicator payload.

NOTE: we will track this bug in a new story:  https://github.com/WideChat/Rocket.Chat/issues/1361
