### ISSUE TITLE
Rocketchat needs to handle escalated sessions in whatsApp conversations.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1363]
Issue:
The twilio integration we use for whatsApp sessions routes always to the defined Dialogflow department in Rocketchat. 

Fix:
Can we track if a particular session is in an escalated state, and when messages from twilio enter the integration can we bypass the configured default department (Dialogflow) and route to the SF department instead? All the while maintaining session state/integrity.

**Comment by ear-dev** [comment]
Hi @bhardwajaditya can you look at this story please and let me know what you think?  I'd like to know if we can come up with a design that we could implement for this. 

It's possible that the whatsApp bots could stay on Rocketchat for a while, and some of our european businesses seem interested in liveagent chat escalation in whatsApp.  It would be nice if we can offer that.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev I will look into this and get back with the answer by tomorrow meeting

**Comment by ear-dev** [comment]
@bhardwajaditya can you please describe your design for this here.  Basically we want to spec the work and understand where and what the changes to accomodate this will be.

**Comment by ear-dev** [comment]
@bhardwajaditya please add your design diagram here.

Lets go ahead and implement.

**Comment by bhardwajaditya** [comment]
![SMS_Flow drawio](https://user-images.githubusercontent.com/23612313/221912122-928fe9fc-bf86-4612-8ac3-8b1286439464.png)
