### ISSUE TITLE
[BUG] Sometimes event_scheduler gets stuck and never runs the job

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1370]
This is happening about a dozen or so times a day right now, only in our Brazil bot.  It's always with those 0 second timer payloads, designed to send a message back immediately from RC to trigger an action on the bot. 

The result is that those sessions get completely stuck because RC is dropping any subsequent messages from the visitor (i.e. blackout window) and we have to close the room to get unstuck.  

This is a hard thing to debug because it is not easily reproducible on demand.  Perhaps we need to take a look at our implementation and see if we have done this in the best way?

Note: it does seem to happen during active periods on the server, and after initial deployment of a new version of DF.app it usually takes a few days or longer for the issue to reappear.

**Comment by ear-dev** [comment]
https://developer.rocket.chat/apps-engine/adding-features/scheduler-api

**Comment by ear-dev** [comment]
Maybe make a flow diagram of the whole process end to end so we can stare at it and think about points of failure.

**Comment by ear-dev** [comment]
Should we consider protecting against stuck events?  i.e. if we schedule a 0 second timer, and we monitor and see that it does not go off, can we just kill it programatically so that the visitor is not stuck? 5mins, 2 mins, 1min?

- **goal is to release the blackout window**....  problem with that is CX will get confused because conversation state is now unexpected. CX not handling context change gracefully??
  - ear to verify
- iterate over how to get the best user experience.

Please check list of relevant events in the enum....  i.e. boleto_pause, verification_pause, others?

We need to be conscious of adding server load and optimizing this.

**Comment by ear-dev** [comment]
Please look at this story for which Alexander originally tried a fix.  There might be some good wrinkles to consider in there.  But we do not want to use CX behavior as our key, we want to track our events to verify that they are not getting stuck.

**Comment by ear-dev** [comment]
@bhardwajaditya 
NOTE:  I met with our CX developers and we have a good design to handle out of context visitor messages that will result in this design if we kill the scheduled  task and release the blackout_window. 

One thing:  we need to figure out a way to test the new feature against the real CX bot in our preprod RC instances.  I think we can create a decent testbot test case for it, but just wondering if there is a more realistic way to test.

**Comment by ear-dev** [comment]
Notes: Looking at the logs and comparing good sessions with bad

- Bad session shows "starting search for triggers" multiple times, and in between scheduling the failed event.
- Need a log point after successful cancelling all events so we can see when it returns and which event_ids it cancelled.

**Comment by ear-dev** [comment]
Status: We discovered that we were using the agenda library incorrectly while scheduling 0 second timer events. 

- we should use 'now' instead of 'once'

**Comment by bhardwajaditya** [comment]
@ear-dev I have raised 3 PRs, if we want to use the master branch of apps-engine then we need to merge and change the package link in other two

**Comment by ear-dev** [comment]
Status:  after deploying the run now fix, we are still seeing the issue:

- We now think there is a race condition with "cancelling all jobs" which happens in the post_message_event_handler. 
- cancelByDataQuery is returning a promise<void>, and it appears that when server under load, this can take up to 550ms. 
- In the meantime we move on and while we are processing the current request, and scheduling the pause events, the cancel all jobs sneaks in and kills the event.

Possible solution:  look into another way to handle the cancelByDataQuery method so that it is blocking.
