### ISSUE TITLE
[DF] Design new timer which sends an event to CX after 15 mins idle time.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#1384]
Use case:

If the visitor is idle for 15 minutes, we would like to trigger CX to send a feedback survey. 
- This would be like Visitor Abandonment since we would have to reset the timer every time the visitor sends a message.
- After 15 mins of inactivity we would send an event to CX ("trigger_feedback" maybe) which would trigger the feedback survey.
- We might also need to reset the VA timer upon sending this new event, so that the visitor will have another 19 mins to answer the survey before the session times out. 

NOTE: This new 'trigger_feedback' event will only be required on some sessions.  The plan would be to only offer a visitor the feedback survey every N number of days (30 or 45 days).  
- Upon initial registration with CX for a new session, CX will send a new flag in the response ('trigger_feedback': true) and if this is present, we would set and track the feedback timer for this session. For all other sessions this would be a NOOP.

**Comment by ear-dev** [comment]
![RC action feedbackSurvey](https://github.com/WideChat/Rocket.Chat/assets/28864717/51fdc6e2-b3c6-4caa-b68d-07e7ee6ab06c)

**Comment by ear-dev** [comment]
@bhardwajaditya we would like to go ahead with this design please.  Can you work on this one next?  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev ok starting with this one

**Comment by ear-dev** [comment]
@bhardwajaditya just a heads up...  our stakeholders have prioritzed this new feature, so we definitely want to get it done within the next week or two if possible.  Thanks!
