### ISSUE TITLE
preferences and profile screens should not have a horizontal slider

### ISSUE THREAD

**Issue by jaytat0** [WideChat/Rocket.Chat#152]
The My Account/Preferences and My Account/Profile screens have a horizontal slider:

![image](https://user-images.githubusercontent.com/8495373/74368378-86829680-4da1-11ea-8bc5-ad9d0848ae0c.png)

Should probably make these fit better so that slider isn't needed. This is example is from a Galaxy S10.

**Comment by shubhsherl** [comment]
![output](https://user-images.githubusercontent.com/34231951/74952851-de1aa500-5426-11ea-844e-72b08dceffa9.gif)
