### ISSUE TITLE
Three Dot Menu not visible when user don't have permission tom create room

### ISSUE THREAD

**Issue by kb0304** [WideChat/Rocket.Chat#161]

**Comment by Shailesh351** [comment]
@kb0304 I was debugging and got to know that create channel only appears when user admin has given permission to create-p, create-c to user.

In dev, create channel/group permission is not given to user. That's why it is not visible. I thought it was some  css issue.

**Comment by Shailesh351** [comment]
For the three dot menu, it is not visible when user don't have create permission. But It should be visible as it contains view mode, sort and share options. I will create PR for the same.
