### ISSUE TITLE
Standardise responsiveness and make it consistent across devices

### ISSUE THREAD

**Issue by kb0304** [WideChat/Rocket.Chat#162]

**Comment by Shailesh351** [comment]
Hi, we will show PWA for media query width < 780px to support both mobile and tablet, (portrait and landscape mode)

The following components needs to be handled for that,
- [ ] Header(Profile Icon, Search Bar, Options)
- [ ] Sidebar (RoomsList)
- [ ] MessageBox

FontSize needs to be fixed for all the above components

**Comment by Shailesh351** [comment]
Issue resolved. Hence Closing.
