### ISSUE TITLE
Admin/users and Admin/rooms UI does not populate.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#196]
This seems to be a regression after the latest upstream catchup merge.  Could it be a backwards compatibility issue? Or a merge mistake?

**Comment by ear-dev** [comment]
![image](https://user-images.githubusercontent.com/28864717/77577176-b21e9380-6eac-11ea-899f-1f0bffa1f150.png)

**Comment by Shailesh351** [comment]
Issue resolved. Hence Closing.
