### ISSUE TITLE
Not possible to enable livechat

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#215]
I've been trying to enable Livechat on our dev server but I can't figure out how that is supposed to work anymore.  Did we lose something in the latest catchup merge?  Or has the system changed and I just don't understand it?

**Comment by ear-dev** [comment]
@Shailesh351 I've been testing Aditya's latest catchup merge PR, and I still can't figure out how to enable Livechat.  I think you suggested that Livechat should work after our latest catchup?  Can you verify where we are with that, and what might be the issue?  Thanks.

**Comment by Shailesh351** [comment]
Issue resolved. Hence closing.
