### ISSUE TITLE
[Upstream Demo] Open/Close Main Content based on URL

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#275]
https://github.com/WideChat/Rocket.Chat/commit/3d665d03078fd3c5261c550ab292557b988dd038#diff-523e0b24928c722fba3217452f96687e

https://github.com/WideChat/Rocket.Chat/commit/f1397d1893c0bd35d22463e3c34cd328d2aa05a4#diff-523e0b24928c722fba3217452f96687e

**Comment by shubhsherl** [comment]
@Shailesh351 I didn't saw this issue earlier, I think I added the required changes #279

**Comment by shubhsherl** [comment]
This is related to [#17375](https://github.com/RocketChat/Rocket.Chat/pull/17375) I guess. You may cherry-pick [this](https://github.com/WideChat/Rocket.Chat/pull/279/commits/9ab0d7af25d1922f35173aa2708bd34f41ea6bcc) commit to update in Upstream PR.

**Comment by Shailesh351** [comment]
Thanks @shubhsherl I will cherry pick your commit in upstream PR

**Comment by Shailesh351** [comment]
Added in Upstream PR https://github.com/RocketChat/Rocket.Chat/pull/17375

**Comment by Shailesh351** [comment]
Issue resolved. Hence Closing.
