### ISSUE TITLE
[Upstream Demo] The chatroom list view is not set as the default start page

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#283]
examples:  
- When first opening the PWA it starts on the Layout page, not on the chatroom list view.
- When closing out the my account page, it takes you to your last chat, and not to the list view.  

Previously we have had fixes for these things

**Comment by ear-dev** [comment]
@Shailesh351 I did merge this PR, but I just tested it and the app still does not open with the chat list view.  The other issue, closing My Account page is now fixed.  Can you take a look and make another PR please?

**Comment by Shailesh351** [comment]
@ear-dev I'm not able to reproduce first one
> When first opening the PWA it starts on the Layout page, not on the chatroom list view.

Can you give more details or something?

**Comment by Shailesh351** [comment]
@ear-dev Very strange behaviour it is only happening after adding app in home screen. I will check start_url for pwa

**Comment by shubhsherl** [comment]
Updated here: https://github.com/RocketChat/Rocket.Chat/pull/17549

**Comment by Shailesh351** [comment]
Issue resolved. Hence Closing. Thanks @ear-dev @shubhsherl !!
