### ISSUE TITLE
upstream catchup into develop_pwa

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#321]
we are still not able to see the games available in the marketplace on our server.  they suggested that maybe another upstream catchup will help.  If not we will have to continue to debug

**Comment by ear-dev** [comment]
@shubhsherl your idea to setup a weekly merge is great!  I have switched our base branch to be develop_pwa.  Can you please create a wiki in our repo that describes our catchup process?  After the Action runs, we'll have to manually merge.....  etc....

Currently we have been catching up with upstream 'develop', but can you look into changing that so we track 'master'?  If we do that, then weekly would not be necessary, and we can trigger our action each time their master gets updated.  Do you think that will work?

Thanks.

**Comment by shubhsherl** [comment]
@ear-dev 
> Can you please create a wiki in our repo that describes our catchup process?

Sure, I'll create a wiki page for it.
> Currently we have been catching up with upstream 'develop', but can you look into changing that so we track 'master'?

I think this is possible, I'll look into it.

**Comment by shubhsherl** [comment]
https://github.com/WideChat/Rocket.Chat/wiki/Upstream-Catchup-using-github-action

**Comment by shubhsherl** [comment]
@ear-dev 
> Currently we have been catching up with upstream 'develop', but can you look into changing that so we track 'master'? If we do that, then weekly would not be necessary, and we can trigger our action each time their master gets updated. Do you think that will work?

I checked about the release based action trigger. It seems like we cannot run the trigger from our repo, based on the upstream releases. We can use some timer-based trigger which can check for new releases and create a catchup PR.

**Comment by ear-dev** [comment]
@shubhsherl The current Action you created is on a timer, right?  So if we just did the same thing against master, that should work, right?  If no changes then there will just be nothing to merge and we should be fine?  

However, since our branch has been tracking develop, and not master, do you think we'll have any issues if we start merging master into our develop_pwa?

**Comment by shubhsherl** [comment]
@ear-dev Yes, it is a timer based action. I don't think there will be any problem for master, it will work in a similar way.
