### ISSUE TITLE
Search bar in the web client does not clean up the previous icons

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#322]

**Comment by ear-dev** [comment]
![image](https://user-images.githubusercontent.com/28864717/85137236-dd482300-b20e-11ea-9436-d37febd8357b.png)

**Comment by Shailesh351** [comment]
@ear-dev I tried to check it from code. In the code it is working good. Then I tried to debug on dev tools and found that value of `--rc-color-primary-darkest` is not proper `##008085`. it should be `#008085`

Can you check value from Admin -> Layout -> Colors -> Primary Darkest.

**Comment by ear-dev** [comment]
@Shailesh351  Good catch.  I fixed the typo and it all looks good.  Thanks for finding that. I'll close this story

**Comment by Shailesh351** [comment]
Issue resolved. Hence closing. Thanks @ear-dev
