### ISSUE TITLE
Viasat Logo is very blur in the Sidebar Footer

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#357]
<img width="870" alt="Screenshot 2020-07-18 at 9 01 55 PM" src="https://user-images.githubusercontent.com/18264684/87856064-fc36f380-c939-11ea-846f-5b8180c5510f.png">

**Comment by Shailesh351** [comment]
@ear-dev To fix this we need to update from Admin Settings.

` Admin -> Layout -> Content -> Side Navigation Footer`

`<a href="/home"><img src="assets/logo.png" alt="Home" /></a>`
In this need to change `logo.png` to `logo.svg`

**Comment by ear-dev** [comment]
Awesome.  thanks.

**Comment by Shailesh351** [comment]
Issue is resolved. So closing it.
