### ISSUE TITLE
Disable the "Update your Rocketchat" warning banner.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#369]

**Comment by ear-dev** [comment]
![image](https://user-images.githubusercontent.com/28864717/88936841-59dc1180-d251-11ea-9abc-b19858f4fb00.png)

**Comment by Shailesh351** [comment]
@ear-dev This banner is only showed to admin users. I did some digging in upstream repo and found that they will provide option to disable version check. Here's the PR https://github.com/RocketChat/Rocket.Chat/pull/18339.

So when we catch up with upstream/master you will be able to disable it from `General -> Update.`

**Comment by ear-dev** [comment]
great.  Thanks for looking into it.  I'll close this.
