### ISSUE TITLE
[BUG] deploying the Livechat app results in an error.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#429]
deploying your app... !
    Error: Deployment compiler errors: 
    [
      {
        "file": "lib/OnUserTypingHandler.ts",
        "line": 4,
        "character": 9,
        "message": "lib/OnUserTypingHandler.ts (5,10): Module 
    '\"/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/d
    efinition/rooms/index\"' has no exported member 'IRoomUserTypingContext'. 
    Did you mean 'IRoomUserJoinedContext'?"
      },
      {
        "file": "SalesforceLiveAgentApp.ts",
        "line": 15,
        "character": 9,
        "message": "SalesforceLiveAgentApp.ts (16,10): Module 
    '\"/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/d
    efinition/rooms/index\"' has no exported member 'IRoomUserTyping'."
      },
      {
        "file": "SalesforceLiveAgentApp.ts",
        "line": 15,
        "character": 26,
        "message": "SalesforceLiveAgentApp.ts (16,27): Module 
    '\"/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/d
    efinition/rooms/index\"' has no exported member 'IRoomUserTypingContext'. 
    Did you mean 'IRoomUserJoinedContext'?"
      }
    ]

**Comment by Shailesh351** [comment]
Issue resolved.
