### ISSUE TITLE
[BUG] Error deploying apps - "could not find class file"

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#444]
I'm seeing this for both LiveAgent and Dialogflow apps.

Error: Deployment error: Invalid App package. Could not find the classFile
     (SalesforceLiveAgentApp.js) file.

**Comment by ear-dev** [comment]
It looks to me like this change in the apps-engine is causing this issue:  https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/71f8a5e9a5e05aaff30a662863cd45b6397141d9#diff-93996513eedba93e0e76f7462cc38a2bbee23058ee8d36a5166ae74ab426b45bR44

The .ts compiler was removed, and the classFile extension is being changed to .js from .ts.  

@Shailesh351 When you are feeling better please have a look.

**Comment by Shailesh351** [comment]
Issue resolved
