### ISSUE TITLE
[Kailash] Setup testbed with RC server (livechat widget), Dialogflow App, Salesforce App.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#466]
https://github.com/WideChat/Apps.Salesforce.LiveAgent

https://github.com/WideChat/Apps.Dialogflow

Chad will send you a wiki with description of the full integration.

**Comment by Shailesh351** [comment]
@Kailash0311  @ear-dev Some video links to get familiar with functionality

https://www.youtube.com/watch?v=-C_k1sRFV9g
https://www.youtube.com/watch?v=RLlYuesDm9k

To setup salesforce account for testing : https://www.youtube.com/watch?v=J5-zEf9MPvc

Also readme of both repo has good documentation to get started

**Comment by Shailesh351** [comment]
Done
