### ISSUE TITLE
[2] After closing chat clear assigned agent from memory

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#468]
if an escalated session is closed, and a new chat started, the session escalates immediately. Closing the chat should always send the end_session dialogflow event.

NOTE: 1/28: this can still be reproduced by having an escalated session timeout, closing the bot, when it re-opens it will immediately escalate

### To reproduce:
- escalate to agent
- 'x' out of client side
- re-open the client, immediately escalates

**Comment by Shailesh351** [comment]
@chadgoss To fix this issue, we need to modify omnichannel settings.

In the Omnichannel -> Departments section, you will need to disable `Show on registration form` for the department which has Salesforce bot as agent. (Or may be only keep `Show on registration form` enabled for the department which has Dialogflow)
