### ISSUE TITLE
[TBD] Live agent queue messages not being displayed

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#472]
1) "Live agent queue empty message": is not displayed, it should be shown when user is next up in the queue. %s to be replaced by the user's queue position

2) "Live Agent Queue Position Message" is not displayed, it should show user his/her current position in the queue. %s will be replaced by the user's queue position

**Comment by Kailash0311** [comment]
@chadgoss Liveagent queue messages only get displayed when queue position is greater than 1. Should we change it to display even when the queue pos is 1?
