### ISSUE TITLE
configurable excluded system messages

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#477]
list of excluded system messages is currently hardcoded, should be configurable
https://github.com/WideChat/Rocket.Chat.Livechat/blob/develop/src/components/helpers.js#L124

**Comment by Shailesh351** [comment]
Adding more details

UI : In the `Admin -> Omnichannel -> LiveChat`
<img width="978" alt="Screenshot 2020-12-08 at 8 00 35 PM" src="https://user-images.githubusercontent.com/18264684/101496756-285a1c00-3990-11eb-9185-9fefd8710294.png">
