### ISSUE TITLE
[5] Allow for LiveAgents to see user text as they type it

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#483]
Enable and function the agent 'sneak peak' ability
probably https://developer.salesforce.com/docs/atlas.en-us.live_agent_rest.meta/live_agent_rest/live_agent_rest_request_bodies.htm#ChasitorSneakPeek

https://help.salesforce.com/articleView?id=live_agent_configuration_settings.htm&type=5

**Comment by Shailesh351** [comment]
The issue is resolved. So closing this issue.
