### ISSUE TITLE
[3] Retain Dialogflow sessions during long-running escalated chats 

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#484]
- When a user escalates to a live agent, they may remain there for an hour or more
- Google's default session timeout is 20 minutes, so as long as the escalated session is alive, the client needs to keep the session with DF alive

When enabled, this feature would tell the app to maintain its session with Dialogflow.

Dialogflow has a default session timeout of 20 minutes, meaning if a user spends >20min in another department and then returns to the bot, Dialogflow would create a new session/sessionID for it and lose any contexts associated with the original chat.

One option to achieve this, is to document an innocuous event like session_maintenance, and have an intent in Dialogflow that accepts it but doesn't have a text response.

When the user closes the widget and terminates the chat, the app can stop maintaining the session and send the chat terminated event #19 (its probably best to cap the maintenance at some configurable max time, like 2 hours, to prevent runaway maintenance processes)

https://stackoverflow.com/questions/53717717/what-is-the-lifetime-of-dialog-flow-session

**Comment by Shailesh351** [comment]
Helpful links

https://stackoverflow.com/questions/53717717/what-is-the-lifetime-of-dialog-flow-session
https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/253#issuecomment-513489384
https://miningbusinessdata.com/extending-context-duration-in-dialogflow/

**Comment by Shailesh351** [comment]
Related PRs

RC Server : https://github.com/WideChat/Rocket.Chat/pull/506
Apps Engine : https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/12
Dialogflow : https://github.com/WideChat/Apps.Dialogflow/pull/36
