### ISSUE TITLE
[3] Send end_session event to dialogflow after chat is closed after escalation

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#496]

**Comment by Shailesh351** [comment]
@chadgoss You will need to configure settings of the Apps for this functionality to work.

In DialogFlow App Settings : 
<img width="895" alt="Screenshot 2020-12-29 at 5 09 33 PM" src="https://user-images.githubusercontent.com/18264684/103281446-ccb40900-49f8-11eb-970a-a2fcd5909ca9.png">

In Salesforce App Settings : 
<img width="895" alt="Screenshot 2020-12-29 at 5 10 15 PM" src="https://user-images.githubusercontent.com/18264684/103281473-da698e80-49f8-11eb-969f-1cba6e9992a8.png">

**Comment by chadgoss** [comment]
@Shailesh351 when the SF agent selects "End Chat": 
- The Salesforce app "Live Agent Chat Ended Message" is displayed in the client widget
- I continue to see `session_maintanence` events
<img width="626" alt="Screen Shot 2021-01-15 at 2 10 18 PM" src="https://user-images.githubusercontent.com/9826215/104768404-94703280-573b-11eb-9313-35b1a8b259e3.png">


also, I don't see the configured 'Dialogflow Agent Ended Chat Event Name'  event getting sent until after the user 'x's out of the bot


The behavior we want is that when the agent selects "End Chat" the configured "Dialogflow Agent Ended Chat Event Name"  event is sent to DF

**Comment by Shailesh351** [comment]
@chadgoss When agent ends chat it responds with `This session has been closed. Have a nice day.` and `Close Chat` button.

<img width="505" alt="Screenshot 2021-01-16 at 9 53 01 AM" src="https://user-images.githubusercontent.com/18264684/104796980-c5567300-57e0-11eb-9054-3ceacac671d3.png">

And when user clicks Close Chat button, then the chat room is closed in RC server and dialogflow event will trigger. This is the current flow.
