### ISSUE TITLE
[2] escalated session: agent ending chat should trigger "Dialogflow Agent Ended Chat Event Name" event

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#568]

**Comment by chadgoss** [comment]
Pulled https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/28
and it's configured 

but, I'm not seeing end_live_chat in either user ends live chat or agent ends live chat

**Comment by Shailesh351** [comment]
The issue is resolved. So closing this issue.
