### ISSUE TITLE
[UX Improvement] User notification when agent ends escalated chat.

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#585]
Notify the user that the agent has ended the chat

Might fix itself after Bug 613

**Comment by chadgoss** [comment]
verify that end_live_chat event is sent

**Comment by chadgoss** [comment]
Pulled https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/28
and it's configured 

but, I'm not seeing end_live_chat in either user ends live chat or agent ends live chat

**Comment by Shailesh351** [comment]
The issue is resolved. So closing this issue.
