### ISSUE TITLE
[BUG] When a user is waiting for live agent in the queue and closes chat, it should cancel chat in the salesforce dashboard

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#586]

**Comment by ear-dev** [comment]
@Shailesh351 Chad and Daniel have verified that this functionality is actually working.  Can you describe what you are seeing and verify that you can reproduce please?

**Comment by Shailesh351** [comment]
@ear-dev I'm also not able to reproduce it now. It's working perfectly.
