### ISSUE TITLE
[PII] Meteor methods and apps are agnostic to log level - verify and fix.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#618]
looks like cronjobs are also agnostic to log level, but that is lower priority.

**Comment by ear-dev** [comment]
I20210427-14:22:06.152(0) livechat:setUpConnection {   id: 'ez85LNfJmDj6ye3hP',   clientAddress: '172.242.112.194',   httpHeaders: {     'x-forwarded-for': '172.242.112.194',     'x-forwarded-host': 'messaging.vega-preprod.viasat.io',     'x-forwarded-port': '443',     'x-real-ip': '172.242.112.194',     'x-forwarded-proto': 'https',     host: 'messaging.vega-preprod.viasat.io',     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36',     'accept-language': 'en-US,en;q=0.9'   },   userId: null } 
I20210427-14:22:14.834(0) listEmojiCustom {   id: 'uznAkqcJh5eGm8nPo',   clientAddress: '10.32.6.198',   httpHeaders: {     host: 'messaging.vega-preprod.viasat.io',     'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1',     accept: '*/*',     'accept-language': 'en-us',     'content-type': 'application/json',     referer: 'https://messaging.vega-preprod.viasat.io/',     'x-forwarded-for': '172.243.250.108, 10.32.6.198',     'x-forwarded-host': 'messaging.vega-preprod.viasat.io',     'x-forwarded-port': '443',     'x-forwarded-proto': 'https',     'x-real-ip': '172.243.250.108',     'x-request-id': '9c2a07e2b365030136be6a495d8ec29d',     'x-scheme': 'https',     'accept-encoding': 'gzip',     connection: 'close'   },   userId: undefined }

**Comment by bhardwajaditya** [comment]
Turning off trace methods under log settings in administration should fix it

**Comment by ear-dev** [comment]
fixed......  thanks.
