### ISSUE TITLE
[logging] Use console.error instead of console.log for escalation failure events in the apps.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#619]
This may be required after we fix log level adherance in apps?

**Comment by Shailesh351** [comment]
Related PRs:

Server : https://github.com/WideChat/Rocket.Chat/pull/638
Apps-Engine : https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/25
DialogFlow : https://github.com/WideChat/Apps.Dialogflow/pull/57
Salesforce App : https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/34

**Comment by Shailesh351** [comment]
The issue is resolved. So closing this issue.
