### ISSUE TITLE
[UI] Chat bubbles in the livechat widget

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#696]

**Comment by itzzritik** [comment]
@ear-dev 
Here's the attached screenshot for the friendly chat in LiveChatWidget

![image](https://user-images.githubusercontent.com/24320496/121979003-fa262080-cda6-11eb-9ee8-0f52f1519d53.png)

I have 2 questions before raising PR.
1. Shall we remove the avatar shown per message
2. Shall we remove timestamp per message

please also provide feedback if any!

**Comment by ear-dev** [comment]
- Add a switch for Avatar presence......  true/false
- Timestamp in bottom right, inside bubble

**Comment by ear-dev** [comment]
@bhardwajaditya when you review this PR can you please check how this looks on different mobile versions, including older versions?  Maybe @Shailesh351 can check as well?

**Comment by bhardwajaditya** [comment]
@ear-dev sure I will have a look with different versions

**Comment by Shailesh351** [comment]
@ItzzRitik Can we align the avatar at the bottom? At the top UI looks a little weird. Also showing rounded avatar will also look cool 🤩

**Comment by itzzritik** [comment]
@Shailesh351 Sure Shailesh, it makes sense
I'll align Avatar at the bottom of last message and make it rounded.

Thanks!

**Comment by itzzritik** [comment]
@Shailesh351 
Hope this was what you were expecting: 
Rounded Avatar positioned at the bottom:


<img src="https://user-images.githubusercontent.com/24320496/123108675-3d902700-d458-11eb-9a37-0710a99682f7.png" width="50%">

**Comment by itzzritik** [comment]
Raised the PR 🎉
1. Friendly UI in Livechat Widget -> [PR Link](https://github.com/WideChat/Rocket.Chat.Livechat/pull/94)
2. Switches for Friendly UI in Livechat Widget -> [PR Link](https://github.com/WideChat/Rocket.Chat/pull/793)

**Comment by Shailesh351** [comment]
@ItzzRitik @chadgoss This is how it looks with buttons.

<img width="1791" alt="Screenshot 2021-06-25 at 7 49 49 PM" src="https://user-images.githubusercontent.com/18264684/123758108-3e074280-d8dc-11eb-99c7-4b896ea17632.png">

@ItzzRitik Did you noticed the rounded corner for the last message? It's looking different because of system messages. Can you fix it, please? Thanks!!
