### ISSUE TITLE
[CX] Verify the whatsApp card format and test sending it from our agent to a whatsApp client through twillio integration.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#727]

**Comment by ear-dev** [comment]
- provide Chad and Steve the spec for a whatsApp rich message (card)
- test that it renders properly in a whatsApp session (after Chad configures a rich message payload in our CX agent)
- Steve will provide a spec describing our rich message requirements.

**Comment by ear-dev** [comment]
https://developers.facebook.com/docs/whatsapp/api/messages/

https://www.twilio.com/docs/whatsapp/tutorial/send-and-receive-media-messages-whatsapp-python

**Comment by AlexanderKanakis** [comment]
External PRs:

Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/69
