### ISSUE TITLE
"Please close this window" depresses as if it should do something

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#734]

**Comment by chadgoss** [comment]
<img width="378" alt="Screen Shot 2021-06-07 at 2 26 07 PM" src="https://user-images.githubusercontent.com/9826215/121070151-5cc25f80-c79c-11eb-9b81-6fd02eb60784.png">

**Comment by AlexanderKanakis** [comment]
### Recommended solution:

The custom payload in the fulfillment which produces the "Please close this window" button should be replaces with the "Close Chat" custom payload added in the Apps.Dialogflow PR :

- https://github.com/WideChat/Apps.Dialogflow/pull/69 
- https://github.com/WideChat/Apps.Dialogflow/pull/79

**Comment by chadgoss** [comment]
we're not getting multiple texts before the window gets closed, only the first line is displayed.
I've tried with multiple text payloads with the same result.

dialogflow history:
```
 "fulfillmentMessages": [
    {
      "text": {
        "text": [
          "I am unable to locate your account information.",
          "Please contact our Customer Care team by phone 24/7 at 1-855-463-9333.",
          "Please close this window to end your chat session."
        ]
      }
    },
    {
      "payload": {
        "action": {
          "name": "df_close_chat"
        }
      }
    }
  ],




```

**Comment by chadgoss** [comment]
<img width="693" alt="Screen Shot 2021-07-09 at 12 45 39 PM" src="https://user-images.githubusercontent.com/9826215/125111162-934d0c00-e0b3-11eb-89e8-ad1396d780d6.png">

**Comment by AlexanderKanakis** [comment]
Please also check PR: https://github.com/WideChat/Apps.Dialogflow/pull/79

**Comment by ear-dev** [comment]
@AlexanderKanakis please adjust these PRs to be against the master branch.
