### ISSUE TITLE
Show commit hash for each App (Dialoglow and Salesforce)

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#740]
If we could easily view the commit hash in the UI that would be nice.

**Comment by ear-dev** [comment]
option 1:  just increment the version number for every PR....  i.e. 1.2.1.001, 1.2.1.002
option2: can we make changes in the apps-cli repo that would pick up the current git hash and apply it somewhere in the settings UI?

**Comment by ear-dev** [comment]
@ItzzRitik can you add links to the relevant PRs here please?

**Comment by itzzritik** [comment]
PR for the frontend: [Link](https://github.com/WideChat/Rocket.Chat/pull/875)
PR for the compiler: [Link](https://github.com/WideChat/Rocket.Chat.Apps-compiler/pull/10)
