### ISSUE TITLE
[BUG - High Priority] Composer on Safari in IOS does not work.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#780]
We need to look at this asap please

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 do one of you have an iPhone?  We need to look at this asap if possible.  Thanks!

**Comment by bhardwajaditya** [comment]
@ear-dev I have android. Can you share some screen recording

**Comment by bizzbyster** [comment]
@bhardwajaditya is there an iOS emulator possibly?

**Comment by Shailesh351** [comment]
<img width="548" alt="Screenshot 2021-06-17 at 7 39 35 AM" src="https://user-images.githubusercontent.com/18264684/122320244-9420d100-cf3f-11eb-856c-9703b6ab13c4.png">
<img width="548" alt="Screenshot 2021-06-17 at 7 39 10 AM" src="https://user-images.githubusercontent.com/18264684/122320261-9aaf4880-cf3f-11eb-9ede-60ccf2cfa3bf.png">

@ear-dev @bizzbyster Composer is not visible only in iOS. I checked the same for open.rocket.chat and the same issue in upstream as well.

**Comment by Shailesh351** [comment]
FYI @ear-dev @bizzbyster You can install XCode and run iOS Simulator on Mac. https://grinchik.com/blog/how-to-install-ios-simulator-and-android-emulator-on-mac

**Comment by ear-dev** [comment]
@bizzbyster @Shailesh351 can the two of you discuss this please?  Shailesh thinks that it works when you 'add to home screen'

**Comment by ear-dev** [comment]
@Shailesh351 since the 'add to homescreen' option is likely an edge case for us anyway, we need to explore the issue when using safari natively on IOS.  We should probably make an issue upstream for it since it repros with open.rocket......  can you create that issue for us please?  Then I can try to escalate to Sing......  but also, we might have to just fix it ourselves if you have some ideas.......  thanks.
