### ISSUE TITLE
[BUG] Chat Three Dot Menu does not work in Mobile View

### ISSUE THREAD

**Issue by Shailesh351** [WideChat/Rocket.Chat#782]
Similar to  https://github.com/RocketChat/Rocket.Chat/issues/21105

Steps
- Open any chat
- Click on the three-dot menu
- Click on any menu item (info, files, etc)

Nothing happens on clicking on the menu item

**Comment by ear-dev** [comment]
@Shailesh351 can you add some description to this one please?  I'm not sure what you are referring to.....  thanks!

**Comment by Shailesh351** [comment]
@ear-dev  https://github.com/RocketChat/Rocket.Chat/issues/21105
