### ISSUE TITLE
Livechat timer should be configurable

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#789]
- Move timer into SF app.... add config item in UI
- Add a new admin config item: Admin/Omnichannel/Livechat/Timer Enabled - determines whether a timer is owned by the livechat client.

**Comment by ear-dev** [comment]
@AlexanderKanakis can you put a link to the PR in this issue please?  Thanks.

**Comment by AlexanderKanakis** [comment]
PRs:

- Apps.Salesforce.LiveAgent: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/37

**Comment by chadgoss** [comment]
@AlexanderKanakis seeing that when the user doesn't respond to agent in the time frame, the chat ends - but there is no notification to the agent, and the case remains in progress?

I'm also seeing that even though the "Chat end" message shows up and the "close chat" button is shown, the agent can still send messages that will get displayed.
