### ISSUE TITLE
Investigate continued conversations in a new room

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#822]
We’re seeing cases of what appears to be a continued conversation, but it’s a new room/session (this could be clicking a link on a closed room from a previous conversation?)

for example: the first payload we get for a new room/session is "queryText': 'Yes, that helped"

Note - there was no welcome event for this room

**Comment by chadgoss** [comment]
<img width="760" alt="Screen Shot 2021-07-09 at 11 52 02 AM" src="https://user-images.githubusercontent.com/9826215/125105093-14a0a080-e0ac-11eb-8407-97d9242803c2.png">



Example: NDiLc9hgGxhGwh7qM

**Comment by Shailesh351** [comment]
@chadgoss That is the case, I was able to reproduce.

<img width="925" alt="Screenshot 2021-07-10 at 10 54 53 AM" src="https://user-images.githubusercontent.com/18264684/125152864-5ba29a80-e16d-11eb-9fc9-2a6db8a1141d.png">

If the chat is closed, nothing should happen when we click on any quickReply button. Looking into it
