### ISSUE TITLE
[UX Improvement] Implement an escalated session countdown timer when timeout configured in the App (not the widget)

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#847]
SF app

**Comment by AlexanderKanakis** [comment]
PRs:

Rocket.Chat.Livechat : https://github.com/WideChat/Rocket.Chat.Livechat/pull/97
Apps.Salesforce.LiveAgent : https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/41

**Comment by ear-dev** [comment]
@AlexanderKanakis I have just tested the task scheduler fix that @Shailesh351 posted, and it is working now.....  I'm ready to merge his two PRs....  one for RC and one for the Salesforce app. 

Can you remind me please what is in this story that we still need?  As I recall, we realized that we did not need some of the original design, and that maybe there was only one PR instead of two that we wanted to keep?  I just don't remember what this story is now adding.  Thanks!

**Comment by AlexanderKanakis** [comment]
PR:
Apps.Salesforce.LiveAgent: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/47

This fix sends a custom message to the client regardless of the timeout handler setting being `widget` or `app`.
