### ISSUE TITLE
Properly log the case where pullMessages on salesforceChatApiEndpoint returns {}

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#854]
const pullMessagesContentParsed = JSON.parse(pullMessagesContent || '{}');

handlers/InitiateSalesforceSessionHandler.ts
properly handle the case where result is {}

Liveagent chat request sent. {“statusCode”:200,“content”:“OK”,“headers”:{“connection”:“close”,“access-control-allow-origin”:“*”,“access-control-allow-credentials”:“true”,“cache-control”:“no-cache”,“pragma”:“no-cache”,“expires”:“-1”,“content-type”:“application/json”,“content-length”:“2”},“data”:null}
Error getting Liveagent response.: TypeError: Cannot read property ‘0’ of undefined

**Comment by chadgoss** [comment]
what's happening is we are getting an undefined response, that case isn't handled properly



161         if (response === undefined) {
162             // Undefined response from Salesforce
163             return {
164                 statusCode: 204,
165                 content: '{}',
166             };
167         }

**Comment by ear-dev** [comment]
we now have sf response logging in debug mode.
