### ISSUE TITLE
[BUG-BLOCKER] DF.app receiving NULL response from the pullMessagesEndpoint against Salesforce instance in preprod

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#856]
We have been able to reproduce this behavior on two servers using the latest RC, DF, and SF versions......  could this be related to the new apps engine?

Chad has a good repro with logging that shows.

**Comment by chadgoss** [comment]
from Dialogflow history:

   ```
  {
      "payload": {
        "action": {
          "params": {
            "salesforceId": "500P000000ALh5PIAT",
            "customDetail": "{\"label\": \"BotTranscript__c\", \"value\": \"\\\"<p><strong>agent</strong>: Hi there! I am a virtual assistant, designed to answer questions about your service.</p><p><strong>agent</strong>: What can I help you with?</p><p><strong>customer</strong>: agent</p><p><strong>agent</strong>: Sorry I wasn't able to address all of your concerns! Would you like me to transfer you to an agent?</p><p><strong>customer</strong>: Chat with agent</p><p><strong>agent</strong>: No problem, I can do that for you.</p>\\\"\", \"entityMaps\": [{\"entityName\": \"LiveChatTranscript\", \"fieldName\": \"BotTranscript__c\"}], \"transcriptFields\": [\"BotTranscript__c\"], \"displayToAgent\": true}",
            "salesforceButtonId": "573P00000004H5F"
          },
          "name": "df_perform_handover"
        }
      }
    }
  ],
```

**Comment by chadgoss** [comment]
from RC logs, `customDetail` is '':

```
I20210723-14:26:33.495(0)? Dialogflow Action:  {"dialogflowSessionID":"zWZk2hjuQuihyxNqF","action":{"params":{"salesforceId":"500P000000ALh5PIAT","customDetail":"","salesforceBu
ttonId":"573P00000004H5F"},"name":"df_perform_handover"}}       
```

**Comment by ear-dev** [comment]
Seems like the customDetail issue was a red herring...  not an issue.  

Specifically we can now confirm that the return from the pullMessages call to Salesforce, after chasitorInit, is Null.  @chadgoss thinks if may be an issue with a bad implementation in Node, an async issue......  but it could also be an issue with the instance of salesforce we're talking to.

‘’’149 export async function pullMessages(http: IHttp, liveAgentUrl: string, affinityToken: string, key: string) {
150   const pullMessagesEndpoint = liveAgentUrl + ‘System/Messages’;
151   const pullMessagesHttpRequest: IHttpRequest = {
152     headers: {
153       ‘X-LIVEAGENT-API-VERSION’: ‘49’,
154       ‘X-LIVEAGENT-AFFINITY’: affinityToken,
155       ‘X-LIVEAGENT-SESSION-KEY’: key,
156     },
157   };  
158   try {
159     console.error(‘CHADDEBUG pull messagesaa’);
160     const response = await http.get(pullMessagesEndpoint, pullMessagesHttpRequest);
161     console.error(‘CHADDEBUG pull messagesbb’, response);
162        
163     if (response === undefined) {
164       console.error(‘CHADDEBUG Undefined response from Salesforce’);
165       // Undefined response from Salesforce

**Comment by chadgoss** [comment]
The issue is that we're getting an undefined response here:

https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/master/helperFunctions/SalesforceAPIHelpers.ts#L142
