### ISSUE TITLE
[BUG] df_close_chat action payload - not showing multiple responses (first one only)

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#871]
Currently when the df_close_chat action is configured in a response payload, only the first of the response text payloads is displayed. Need to display all of them.

PR Link - https://github.com/WideChat/Apps.Dialogflow/pull/99

**Comment by chadgoss** [comment]
in the configured intent shown here, only the first text payload is displayed before the close_chat button is displayed


<img width="798" alt="Screen Shot 2021-08-02 at 3 31 45 PM" src="https://user-images.githubusercontent.com/9826215/127913752-f1cbcf22-3fbf-440b-8671-1e839ea4cb68.png">

**Comment by ear-dev** [comment]
@chadgoss is this a bug then?

**Comment by ear-dev** [comment]
@bhardwajaditya verify in the DF api spec that custom payloads are concatenated in a single message.  @chadgoss to reproduce.
