### ISSUE TITLE
[DF.APP] Never attempt a handover unless Target Department is configured.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#877]
Is there some hard coded fallback in our DF app that automatically tries to escalate on some error conditions?

We do not want to attempt an escalation in the case where no SF app exists. 

When there is no "Target Department For Handover" there should never be an attempted handover.

**Comment by ear-dev** [comment]
@ItzzRitik If @Shailesh351 is busy can you look at this one please?

**Comment by itzzritik** [comment]
@ear-dev Sure 👍

**Comment by Shailesh351** [comment]
@ItzzRitik 

<img width="1790" alt="Screenshot 2021-08-24 at 9 26 04 PM" src="https://user-images.githubusercontent.com/18264684/130649747-3985c972-6233-40ca-82b0-db41346e9126.png">
<img width="1790" alt="Screenshot 2021-08-24 at 9 26 20 PM" src="https://user-images.githubusercontent.com/18264684/130649759-4306715a-bdb3-4a79-acc1-c5398e6e18cc.png">

**Comment by itzzritik** [comment]
@Shailesh351 
Thanks 👏

**Comment by itzzritik** [comment]
PR raised -> [LINK](https://github.com/WideChat/Apps.Dialogflow/pull/98)
