### ISSUE TITLE
[BUG] DF - App should respect no input when configured as a configuration value; "Service Unavailable Message" for example

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#878]
config/Settings.ts:    DEFAULT_DialogflowServiceUnavailableMessage = 'There are no agents currently available. Our Customer Care team is available by phone 24/7 at 1-855-463-9333.',
config/Settings.ts:        packageValue: DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage,
handler/OnAgentUnassignedHandler.ts:                    { text: offlineMessage ? offlineMessage : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
handler/OnAgentAssignedHandler.ts:                                { text: serviceUnavailable ? serviceUnavailable : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
handler/PostMessageSentHandler.ts:                { text: serviceUnavailable ? serviceUnavailable : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
lib/responseParameters.ts:                            { text: serviceUnavailable ? serviceUnavailable : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
lib/sendWelcomeEvent.ts:        await createMessage(rid, read, modify, { text: serviceUnavailable ? serviceUnavailable : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
lib/payloadAction.ts:                                            { text: serviceUnavailable ? serviceUnavailable : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
lib/payloadAction.ts:                            { text: serviceUnavailable ? serviceUnavailable : DefaultMessage.DEFAULT_DialogflowServiceUnavailableMessage });
ubuntu@ip-172-31-47-156:~/Apps.DialogflowCX$

**Comment by ear-dev** [comment]
@ItzzRitik if @Shailesh351 is busy can you take this one as well please?  Maybe the two of you can sync up on it.

**Comment by itzzritik** [comment]
@ear-dev Sure 👍

**Comment by Shailesh351** [comment]
@chadgoss If some value is set in the DF App setting, It is using it properly. If it is blank then it uses default from code.

**Comment by ear-dev** [comment]
@chadgoss @Shailesh351 Isn't the issue here that we would like an empty string to be accepted if we leave the entry blank?  We do not want the service to default to the default if there is no entry.  Is this a quick fix?

**Comment by Shailesh351** [comment]
Yes @ear-dev, We can remove the default from the code, so that it will only depend on setting
