### ISSUE TITLE
[BUG][ResUS-UX] stuck at "Starting chat" when opening a new tab after "please close this window"

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#892]
to reproduce:
 1) Start chat and get to the state where bot sends "Please close this window" 
2) Go back(back arrorw) on mobile 
3) Again click "Chat now"

PR Link - https://github.com/WideChat/Rocket.Chat.Livechat/pull/101

**Comment by chadgoss** [comment]
<img width="412" alt="Screen Shot 2021-08-19 at 10 41 16 AM" src="https://user-images.githubusercontent.com/9826215/130088843-9bcae1e6-9b97-4da7-9383-1a86ebd18f89.png">

**Comment by ear-dev** [comment]
Is this still reproducible?

Back arrow on mobile is the same as closing the tab in web.......  does it reproduce their as well?
