### ISSUE TITLE
[ResUS-UX] Remove print chat option in mobile only

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#897]

**Comment by ear-dev** [comment]
@chadgoss is this a question?  Who is going to answer this question?  Seems like a question for Steve maybe?

**Comment by ear-dev** [comment]
create a flag in the integration.js script that lets us know to hide the print option.

work: find the flag, and use it to hide the option.
similiar to "show widget" and "hide widget".......  new option is "hide_print"

https://developer.rocket.chat/api/livechat-api

**Comment by itzzritik** [comment]
@ear-dev
Raised the PR => [LINK](https://github.com/WideChat/Rocket.Chat.Livechat/pull/103)
