### ISSUE TITLE
CX: send roomId and visitorToken with all requests so fulfillment can do transcript retrieval

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#899]

**Comment by chadgoss** [comment]
currently for whatsapp, RC is sending the “username” parameter that contains the whatsapp number. We need to also send the roomId and visitorToken in every webhook call

**Comment by ear-dev** [comment]
@AlexanderKanakis has this already been implemented?  Can you sync up with @Shailesh351 on this please?  This is currently our highest priority for releasing our Brazil Bot......  hopefully on Friday this week!!
