### ISSUE TITLE
[js integration script] Document in a wiki how we can mock and test changes

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#922]
This is the first step toward owning the livechat integration component

- post a copy of the current script into the wiki please.
- document how the script is used
- document what the script provides

**Comment by ear-dev** [comment]
@Shailesh351 have you started a wiki for this yet by any chance?  I'm looking for an easy way to find the script.....  thanks

**Comment by Shailesh351** [comment]
https://github.com/WideChat/Rocket.Chat/wiki/LiveChat-Widget-Integration
