### ISSUE TITLE
[CX UX] On-Off switch for toggling concatenated messages.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#928]
Can we put an Admin config item in the CX UI that would allow for toggling concatenated messages that Alexander recently implemented by parsing the responsType in the Diagnostics object?

**Comment by ear-dev** [comment]
@AlexanderKanakis Since we are in the process of migrating our UsRes chatbot to CX, we would like to have this admin config available in the df config.json if possible.  

- In UsRes the primary channel is through the widget, and in this case we do not want to concatenate messages.  This gives the CX developer more control over how the conversation will look.
- In the Brazil / WhatsApp case we want to keep concatenation. 

Having the option to set `concatenate_messages`: true/false will give us the control we need.

**Comment by AlexanderKanakis** [comment]
Related PRs: https://github.com/WideChat/Apps.Dialogflow/pull/154
