### ISSUE TITLE
[BUG] Timeout enabled even after chat is closed

### ISSUE THREAD

**Issue by bhardwajaditya** [WideChat/Rocket.Chat#931]

**Comment by ear-dev** [comment]
@bhardwajaditya can you add some more detail here please, describing how you reproduce.....  thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev you can refer Shailesh's comment here to reproduce this.

https://github.com/WideChat/Apps.Dialogflow/pull/99#pullrequestreview-740982577

**Comment by ear-dev** [comment]
@bhardwajaditya I'm going to move this back to "In Progress".  Please comment and summarize in this issue where we are right now with this bug.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev we have two issues with this story now.

1. The one mentioned here, idle timeout can still be there post chat close.
2. The second issue is when two tabs are open, the timer is cleared in one tab but not other and it remains there even after a message is sent. This can lead to chat timing out even after user sends a message

**Comment by bhardwajaditya** [comment]
@ear-dev raised the PR for this issue. This will fix both the above mentioned issues

**Comment by ear-dev** [comment]
@bhardwajaditya great!  I will test
