### ISSUE TITLE
[DF] Add the roomID to all rest api console.error messages

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#935]
We would like to include the RoomId with http error messages.  Something along the same way we did it with the Failed To Handover messages.  These 4 please:
-     HTTP_REQUEST_ERROR = 'Error occurred while sending a HTTP Request',
-    DIALOGFLOW_REST_API_ERROR = 'Error occurred while using Dialogflow Rest API. Details:-',
-     INVALID_RESPONSE_FROM_DIALOGFLOW = 'Error!! Invalid Response From Dialogflow',
-INVALID_RESPONSE_FROM_DIALOGFLOW_CONTENT_UNDEFINED = 'Error Parsing Dialogflow\'s Response. Content is undefined',

**Comment by itzzritik** [comment]
@ear-dev PR Raised [Link](https://github.com/WideChat/Apps.Dialogflow/pull/107) 🙌
