### ISSUE TITLE
[BUG-linked with 871][CX] Timeout payload handling broken when there are back-to-back df_set_timeout payloads in subsequent turns

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#940]
Molly found a bug in the Rocket.chat timeout payload handling in the DialogFlow CX app. Basically, when there are back-to-back df_set_timeout payloads in subsequent turns, the second timeout is not getting triggered. 

I updated our nonprod “loop” intent to provide a test case.

If you say loop, it should go into an infinite loop of saying “looping” every 3 seconds, until you manually close the room in Rocket.chat. Instead, it only repeats once. 

If you then type CONFIRM twice, it will start the loop again. So multiple df_set_timeout payloads in non-subsequent turns work.

To break down the order of events:
 
Conversation Turn 1:
User types “loop”
DialogFlow responds with “looping” and the below “df_set_timeout” payload
Rocket.chat sets 3 second timer

Turn 2:
At the end of the above timer, Rocket.chat sends an event named LoopEvent
DialogFlow responds with “looping” and another “df_set_timeout” payload
Rocket.chat should set a new 3 second timer, but doesn’t appear to be. We suspect that since this turn was triggered by a timer, that previous timer isn’t getting cleaned up properly and interfering with this one.

Turn 3:
User says “CONFIRM”
DialogFlow responds with “Break page, type CONFIRM to go back to loop”

Turn 4:
User types “CONFIRM”
DialogFlow responds with “looping” and the below “df_set_timeout” payload
Rocket.chat sets 3 second timer -> this timer works now, possibly because this turn was initiated with user input rather than a timer

Turn 5:
Repeats turn 2
 
Here is the sample df_set_timeout payload we are using.
 
{
  "action": {
    "params": {
      "eventName": "LoopEvent",
      "time": 3
    },
    "name": "df_set_timeout"
  }
}

**Comment by ear-dev** [comment]
@Shailesh351 @bhardwajaditya can one of you take a look at this please?  We seem to have misplaced this issue and would like to get it fixed asap if possible.  Thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev I have raised the PR to fix this issue
