### ISSUE TITLE
[DF] Increase the default HTTP response timeout value

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#950]
Currently the default is 10 seconds, but our DF webhook timeout is set to 30s, and some of the calls to DF require more time than 10s to poll the backend for user data.  

Increase to 35s?

**Comment by ear-dev** [comment]
@AlexanderKanakis any chance you can get this one in quick?  must be trivial?  thanks.

**Comment by AlexanderKanakis** [comment]
@ear-dev Ready

PR: https://github.com/WideChat/Apps.Dialogflow/pull/110
