### ISSUE TITLE
[Livechat Troubleshooting] Implement UI logs to capture client actions and state to help understand the missing welcome_event issues we encounter.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#957]
We should figure out which metrics we want to capture.  We do not want to collect PII.

We would like to know:
 - Did a close chat event occur
 - Did it come from the visitor, the timeout timer, or the agent.
 - Was the composer enabled or disabled after a close chat event.
 -  Was the widget minimized or did it remain open after the close chat event.
 - What sequence of events resulted in a new session/room being created.
 - How many tabs were open.
 - ??

**Comment by ear-dev** [comment]
@bhardwajaditya @Shailesh351 Can we explore using the Admin/Omnichannel/Livechat/Send Visitor Navigation History as a Message path, to send our own logs which will track events.  Needs design. Consider optimization and storage.

**Comment by ear-dev** [comment]
@bhardwajaditya please design a temporary UI logger that we can easily implement and remove when we have figured out the issues.  Make a diagram please, and show me exactly what needs to be on the receiving side. 

Put it behind a switch. 

Track the performance impact.....

**Comment by ear-dev** [comment]
@bhardwajaditya are we still waiting on the PRs for this?

**Comment by bhardwajaditya** [comment]
@ear-dev yes fixing it, actually even with was native library methods there's some dependency conflict . Trying to fix those

**Comment by ear-dev** [comment]
@bhardwajaditya can you add links to the relevant PRs here please?  thanks.

**Comment by bhardwajaditya** [comment]
Server PR - https://github.com/WideChat/Rocket.Chat/pull/985
Livechat PR - https://github.com/WideChat/Rocket.Chat.Livechat/pull/110
