### ISSUE TITLE
RC upstream catchup

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#959]

**Comment by Shailesh351** [comment]
App-engine: https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/38
Apps-compiler: https://github.com/WideChat/Rocket.Chat.Apps-compiler/pull/12
Apps-cli: https://github.com/WideChat/Rocket.Chat.Apps-cli/pull/12

Server: https://github.com/WideChat/Rocket.Chat/pull/970
DialogFlow App: https://github.com/WideChat/Apps.Dialogflow/pull/113 
Salesforce App: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/45
