### ISSUE TITLE
[CX] Connection draining in the case we change the Prod CX endpoint on the fly.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#964]
We are designing a system where new Production CX deployments will come in the form of new Agents with new endpoints.  

We will want to update the DF.app on the Prod RC server to point at the new Agent during every CX update/promotion.  

When we do this it should be seamless......  and we should not lose any chats that are currently live at the time of the swap.  The live chats should continue the conversation against the original Agent, but all new chats should be directed at the newly configured Agent.

**Comment by ear-dev** [comment]
This will be for re-usable CX only. 

Basically we will add a new mapping for CX.agent.New, to replace CX.agent.Current......  but we want any rooms against the current agent to be active for their normal lifespan.....  but all new conversations go to the New agent.

**Comment by AlexanderKanakis** [comment]
PR:

Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/125

### Warning:
This story and story https://github.com/WideChat/Rocket.Chat/issues/995 are solved by the same Apps.Dialogflow PR

**Comment by ear-dev** [comment]
@AlexanderKanakis please make a note in this story when you have merged the connection draining and the multiple endpoint configs into a single PR.
