### ISSUE TITLE
[BUG][DF] when using CX the environment value is not being applied such that all conversations are talking with 'draft'

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#969]
maybe it's just not abiding by the setting and only using the default
if that is the case, please confirm that all values we manually set in the UI are being applied
obviously many of them are being applied, or we could not even be talking to the DF.agent...... but there might be others that are failing and we didn't even notice
or maybe we're not using the environment correctly in our connections to DF.CX only

**Comment by AlexanderKanakis** [comment]
PR: https://github.com/WideChat/Apps.Dialogflow/pull/111
