### ISSUE TITLE
[blocked on Freds design] Encrypted whatsApp phone number

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#980]
explanation below, we should also have some way to know if the phone number is encrypted or not - so we can update fulfillment first and RC later.

We need to store the WhatsApp number in the clear (not hashed or encrypted) in IRA.   This is for three main reasons:
Easier for us to debug customer access problems.   Customer care isn’t going to recognize a hash or be able to tell if that is the number we have on file for them
Customer Care needs to be able to update or change the number in case they don’t or are having problems doing it through the app.
No other customer contact information is stored in a hashed/encrypted manner in IRA.
 
So, all this means is that instead of RC eventually hashing the number, we need RC to encrypt it instead.   This way fulfillment can decrypt it for storage in IRA in the clear.

**Comment by ear-dev** [comment]
We will need a production key and provide access to fulfillment.  Perhaps we need a preprod key as well?

**Comment by ear-dev** [comment]
The latest thinking is that this is not in fact required any more.  We'll see.........  :-)
