### ISSUE TITLE
Rocke.Chat Livechat ERROR: Error occurred while using Dialogflow Rest API.

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#982]
We see this error 2-3 times/day

Rocke.Chat Livechat ERROR: Error occurred while using Dialogflow Rest API. Details:-: { roomID: c9eEaEyDQh4c8mSqu } undefined

**Comment by ear-dev** [comment]
@chadgoss I believe that this indicates that the response object is null......  therefore we can't parse any error message or stack trace.  Can you see any corresponding logpoint in CX that indicates the response was sent?
