### ISSUE TITLE
Setup elasticsearch to catch UI logs from Aditya's logger

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#983]

**Comment by chadgoss** [comment]
domain endpoint: https://search-rcec-ylb2uvbhsfetetfdevncnb7o2i.us-east-1.es.amazonaws.com

**Comment by ear-dev** [comment]
@chadgoss can you create a wiki please that documents how to reach and use this elastic instance?  Maybe with some notes about how it is integrated with the livechat widget......  thanks.
