### ISSUE TITLE
[Re-Usable CX][Issue] SMS incoming sessions are linked to the designated room by source phone number.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#991]
The re-usable CX implementation is working great.  With this setup described below, it is working as designed.

- TwilioNumber1 points to departmentID1 -> omnichannelAgent1 -> CX.agent1
- TwilioNumber2 points to departmentID2 -> omnichannelAgent2 -> CX.agent2

Issue:

- If I use a single source phone number (my cell) while testing, then the system breaks because RC will recognize that there is currently an open room linked with my cell phone number, and route me to the existing open room, no matter which TwillioNumber I have called.
- The bad result now looks like this:  TwilioNumber2 -> omnichannelAgent1 -> CX.agent1
- Manually closing the room will reset everything and allow the correct mapping of TwilioNumber to Department.

What do we think the fix should be?  Probably we need to close the first room if we see a new call to the endpoint with a different departmentID?  I think this is an edge case, but that we should handle it properly....  thoughts?

**Comment by Shailesh351** [comment]
@ear-dev Yes as per https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/imports/server/rest/sms.js#L76 currently it is only considering `visitorToken` to find the room. So if there is one open chat in departmentID1, and the user starts chat with TwillioNumber2 it will still find that open room in departmentID1 and will continue the chat.

What we can do is also consider `departmentId` along with token for finding open room https://github.com/RocketChat/Rocket.Chat/blob/develop/app/models/server/models/LivechatRooms.js#L282
