### ISSUE TITLE
[ES migration to CX] Investigate new UI in the DF.app which would allow us to add one json config at a time, instead of multiple endpoints in a single json.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#995]
motivation:  We will need to add the currently global configs we use in ES to the json config file, and this could get large and unwieldy.

**Comment by ear-dev** [comment]
Nothing global except log level.

**Comment by ear-dev** [comment]
Still need to add ALL global configs to the json.

**Comment by AlexanderKanakis** [comment]
PR: 

Apps.Dialogflow: https://github.com/WideChat/Apps.Dialogflow/pull/125
RC: https://github.com/WideChat/Rocket.Chat/pull/981

### Warning:
This story and story https://github.com/WideChat/Rocket.Chat/issues/964 are solved by the same Apps.Dialogflow PR

**Comment by ear-dev** [comment]
@AlexanderKanakis will make a new PR against the apps-engine repo, in response to Shailesh review.

**Comment by AlexanderKanakis** [comment]
PR:

Apps.Dialogflow: WideChat/Apps.Dialogflow#125
RC: #981
Apps-engine: https://github.com/WideChat/Rocket.Chat.Apps-engine/pull/44

<hr>

If the PRs need to be tested before the Apps-engine PR is merged:
1. Change the URL for Apps-engine in package.json to: 
        ```"devDependencies": {
        "@rocket.chat/apps-engine": "git+https://github.com/WideChat/Rocket.Chat.Apps-engine.git#multicode_setting_type"
        }```
        in both **Rocket.Chat** and **Apps.Dialogflow** repos.
2. Run `npm install @rocket.chat/apps-engine` in both **Rocket.Chat** and **Apps.Dialogflow** repos.
